song_intro = 0
song_sword = 1
song_sword_2 = 2
song_northernlight = 3
song_northernlight_2 = 4
song_glaceir = 5
song_bit_roots = 6
song_eram = 7
song_burning_eyes = 8
song_twisted = 9
song_max = 10

.if SONG_STRINGS
song_strings:
.asciiz "INTRO"
.asciiz "SWORD"
.asciiz "SWORD 2"
.asciiz "NORTHERNLIGHT"
.asciiz "NORTHERNLIGHT 2"
.asciiz "GLACEIR"
.asciiz "BIT ROOTS"
.asciiz "ERAM"
.asciiz "BURNING EYES"
.asciiz "TWISTED"
.endif
