; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for MANTLE:
; FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
; FAMISTUDIO_USE_FAMITRACKER_DELAYED_NOTES_OR_CUTS = 1
; FAMISTUDIO_USE_RELEASE_NOTES = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_DELTA_COUNTER = 1

.export _music_data_mantle:=music_data_mantle

music_data_mantle:
	.byte 10
	.word @instruments
	.word @samples-4
; 00 : INTRO
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 286,238
; 01 : SWORD
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 296,247
; 02 : SWORD 2
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 266,221
; 03 : NORTHERNLIGHT
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 436,363
; 04 : NORTHERNLIGHT 2
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 436,363
; 05 : GLACEIR
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.word 342,285
; 06 : BIT ROOTS
	.word @song6ch0
	.word @song6ch1
	.word @song6ch2
	.word @song6ch3
	.word @song6ch4
	.word 282,235
; 07 : ERAM
	.word @song7ch0
	.word @song7ch1
	.word @song7ch2
	.word @song7ch3
	.word @song7ch4
	.word 307,256
; 08 : BURNING EYES
	.word @song8ch0
	.word @song8ch1
	.word @song8ch2
	.word @song8ch3
	.word @song8ch4
	.word 307,256
; 09 : TWISTED
	.word @song9ch0
	.word @song9ch1
	.word @song9ch2
	.word @song9ch3
	.word @song9ch4
	.word 307,256

.export music_data_mantle
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env57,@env28,@env37,@env0 ; 00 : SWORD Pluck
	.word @env45,@env28,@env41,@env0 ; 01 : SWORD Harmony NoEnv
	.word @env20,@env28,@env41,@env0 ; 02 : BE Bass
	.word @env29,@env28,@env46,@env0 ; 03 : BE High Layer
	.word @env45,@env28,@env8,@env0 ; 04 : SWORD Harmony
	.word @env20,@env28,@env37,@env0 ; 05 : Blank
	.word @env16,@env52,@env37,@env0 ; 06 : SWORD Drums
	.word @env2,@env28,@env37,@env44 ; 07 : BE Crash
	.word @env20,@env54,@env38,@env0 ; 08 : BE Tom
	.word @env10,@env28,@env36,@env0 ; 09 : SWORD Lead
	.word @env10,@env31,@env51,@env27 ; 0a : TWISTED Top Arp
	.word @env10,@env28,@env51,@env27 ; 0b : TWISTED Lead 1
	.word @env40,@env28,@env37,@env34 ; 0c : SWORD Thin
	.word @env30,@env28,@env38,@env0 ; 0d : INTRO No Controller
	.word @env43,@env28,@env33,@env27 ; 0e : TWISTED Lead 2
	.word @env6,@env28,@env21,@env0 ; 0f : GLACEIR
	.word @env49,@env28,@env41,@env0 ; 10 : INTRO Mantle Arp
	.word @env45,@env28,@env37,@env0 ; 11 : SWORD Harmony Thin
	.word @env20,@env28,@env15,@env22 ; 12 : SWORD Intro
	.word @env53,@env28,@env37,@env0 ; 13 : SWORD Waves
	.word @env12,@env28,@env33,@env0 ; 14 : TWISTED Lead 2b
	.word @env5,@env24,@env38,@env0 ; 15 : BE Pad?
	.word @env60,@env28,@env38,@env0 ; 16 : NL2 Lead
	.word @env1,@env28,@env47,@env0 ; 17 : BE Lead 1
	.word @env20,@env28,@env37,@env0 ; 18 : ERAM
	.word @env18,@env28,@env37,@env0 ; 19 : BR Noise
	.word @env17,@env28,@env41,@env0 ; 1a : BR Bass
	.word @env10,@env58,@env47,@env27 ; 1b : TWISTED Top Arp 2
	.word @env55,@env28,@env38,@env0 ; 1c : NL Lead
	.word @env9,@env3,@env37,@env0 ; 1d : INTRO Swoosh 2
	.word @env9,@env35,@env37,@env0 ; 1e : INTRO Swoosh 1
	.word @env20,@env28,@env11,@env0 ; 1f : INTRO Heart
	.word @env7,@env28,@env32,@env0 ; 20 : BE Lead 2
	.word @env50,@env13,@env37,@env0 ; 21 : TWISTED Swoosh

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$00,$08
@env2:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$00,$15
@env3:
	.byte $c1,$0f,$c5,$0f,$c2,$0f,$c7,$0f,$c1,$0f,$c4,$0f,$c3,$0f,$c4,$05,$c5,$05,$c6,$05,$c7,$05,$c8,$05,$c9,$05,$ca,$05,$cb,$05,$cc,$05,$cd,$05,$ce,$05,$cf,$00,$24
@env4:
	.byte $00,$c0,$ba,$b7,$ba,$c0,$c6,$c9,$c6,$00,$01
@env5:
	.byte $00,$c5,$ca,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$11
@env6:
	.byte $00,$c1,$c3,$c4,$c6,$c7,$c9,$ca,$cc,$cd,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$00,$11
@env7:
	.byte $00,$cf,$1f,$ce,$1f,$cc,$00,$05
@env8:
	.byte $c0,$c0,$c1,$00,$02
@env9:
	.byte $00,$cf,$7f,$3f,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$20
@env10:
	.byte $0e,$c3,$c7,$cb,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$00,$0b,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$00,$1a
@env11:
	.byte $c1,$0f,$c0,$00,$02
@env12:
	.byte $00,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$00,$0f
@env13:
	.byte $c0,$c0,$bf,$bf,$be,$be,$bd,$bd,$bc,$bc,$bb,$bb,$ba,$ba,$b9,$b9,$b8,$b8,$b7,$b7,$b6,$b6,$b5,$b5,$b4,$b4,$b3,$b3,$b2,$b2,$b1,$00,$1e
@env14:
	.byte $00,$c0,$bf,$be,$be,$bf,$c1,$c2,$c2,$c1,$00,$01
@env15:
	.byte $c0,$03,$c1,$00,$02
@env16:
	.byte $00,$cf,$cd,$cb,$c8,$c6,$c3,$c1,$c0,$00,$08
@env17:
	.byte $00,$ca,$17,$c9,$17,$c8,$17,$c7,$17,$c6,$17,$c5,$17,$c4,$15,$c3,$14,$c2,$14,$c1,$00,$13
@env18:
	.byte $00,$c1,$03,$c2,$03,$c3,$03,$c4,$03,$c5,$03,$c6,$03,$c7,$03,$c8,$03,$c9,$03,$ca,$03,$cb,$03,$cc,$03,$cd,$13,$cc,$07,$cb,$07,$ca,$07,$c9,$07,$c8,$07,$c7,$07,$c6,$07,$c5,$07,$c4,$07,$c3,$00,$2d
@env19:
	.byte $00,$c0,$c0,$bf,$bf,$be,$02,$bd,$03,$bc,$0a,$bd,$03,$be,$02,$bf,$bf,$c0,$02,$c1,$c1,$c2,$02,$c3,$03,$c4,$0a,$c3,$03,$c2,$02,$c1,$c1,$c0,$00,$01
@env20:
	.byte $00,$cf,$7f,$00,$02
@env21:
	.byte $c2,$c0,$c1,$00,$02
@env22:
	.byte $00,$c0,$c0,$c1,$c2,$c2,$c1,$c0,$c0,$bf,$be,$be,$bf,$00,$01
@env23:
	.byte $00,$c0,$02,$bf,$05,$be,$0e,$bf,$05,$c0,$04,$c1,$05,$c2,$0e,$c1,$05,$c0,$c0,$00,$01
@env24:
	.byte $c0,$c0,$c5,$c5,$c0,$cc,$c5,$c5,$00,$00
@env25:
	.byte $00,$c0,$05,$bf,$14,$c0,$0a,$c1,$14,$c0,$03,$c0,$00,$01
@env26:
	.byte $00,$c0,$bf,$bf,$be,$be,$bd,$bd,$bc,$bc,$bb,$02,$ba,$08,$bb,$02,$bc,$bc,$bd,$bd,$be,$be,$bf,$bf,$c0,$c1,$c1,$c2,$c2,$c3,$c3,$c4,$c4,$c5,$02,$c6,$08,$c5,$02,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$00,$01
@env27:
	.byte $00,$c0,$0f,$bf,$be,$bf,$c0,$c1,$c2,$c1,$c0,$00,$03
@env28:
	.byte $c0,$7f,$00,$01
@env29:
	.byte $00,$c5,$c4,$c2,$c1,$00,$04
@env30:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$00,$06
@env31:
	.byte $c0,$cc,$d8,$00,$00
@env32:
	.byte $c0,$02,$c1,$c1,$c1,$00,$00
@env33:
	.byte $c0,$c0,$c2,$c2,$c1,$00,$04
@env34:
	.byte $00,$c0,$0c,$c0,$c0,$c1,$c2,$c2,$c1,$c0,$c0,$bf,$be,$be,$bf,$00,$03
@env35:
	.byte $c0,$03,$c1,$c1,$c2,$c2,$c3,$c3,$c4,$c4,$c5,$c5,$c6,$c6,$c7,$c7,$c8,$c8,$c9,$c9,$ca,$ca,$cb,$03,$ca,$03,$cb,$03,$ca,$03,$cb,$03,$ca,$03,$cb,$03,$ca,$03,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$03,$c2,$03,$c3,$03,$c2,$03,$c3,$03,$c2,$03,$c3,$03,$c2,$03,$c3,$c3,$c4,$c4,$c5,$c5,$c6,$c6,$c7,$c7,$c8,$c8,$c9,$c9,$ca,$ca,$cb,$03,$ca,$03,$cb,$03,$ca,$03,$cb,$03,$ca,$03,$cb,$03,$ca,$03,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$03,$c2,$03,$c3,$03,$c2,$03,$c3,$03,$c2,$03,$c3,$03,$c2,$00,$7c
@env36:
	.byte $c1,$c1,$c2,$00,$02
@env37:
	.byte $7f,$00,$00
@env38:
	.byte $c2,$7f,$00,$00
@env39:
	.byte $00,$c0,$bc,$ba,$bb,$be,$c2,$c5,$c6,$c4,$00,$01
@env40:
	.byte $00,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$00,$0b
@env41:
	.byte $c1,$7f,$00,$00
@env42:
	.byte $00,$c0,$b0,$ac,$b7,$c9,$d4,$d0,$00,$01
@env43:
	.byte $1a,$c1,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$00,$17,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$00,$26
@env44:
	.byte $00,$c1,$03,$c0,$02,$c0,$00,$03
@env45:
	.byte $00,$c8,$7f,$00,$02
@env46:
	.byte $c0,$c2,$00,$00
@env47:
	.byte $c0,$c1,$00,$00
@env48:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env49:
	.byte $00,$cf,$02,$ce,$cd,$cb,$c8,$c4,$c0,$00,$08
@env50:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$00,$13
@env51:
	.byte $c0,$c0,$c1,$c1,$c2,$00,$04
@env52:
	.byte $c1,$c1,$c0,$c0,$bf,$bf,$be,$00,$06
@env53:
	.byte $00,$c1,$03,$c4,$03,$c3,$03,$c8,$03,$c6,$04,$cc,$04,$cf,$0a,$cd,$08,$c9,$0a,$c6,$0a,$c2,$05,$c1,$0a,$c2,$07,$c1,$07,$c2,$09,$c1,$36,$c0,$00,$21
@env54:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$b5,$b4,$b3,$b2,$b1,$00,$0f
@env55:
	.byte $00,$cc,$09,$c5,$00,$03
@env56:
	.byte $00,$c0,$c0,$bf,$03,$be,$04,$bd,$0a,$be,$04,$bf,$03,$c0,$02,$c1,$03,$c2,$04,$c3,$0a,$c2,$04,$c1,$03,$c0,$00,$01
@env57:
	.byte $00,$cc,$cb,$c9,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0a
@env58:
	.byte $c0,$c0,$cc,$cc,$d8,$d8,$00,$00
@env59:
	.byte $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01
@env60:
	.byte $00,$c9,$1d,$c3,$00,$03

@samples:
	.byte $09+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0f,$40 ; 00 Kick (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0f,$40 ; 01 Snare (Pitch:15)

@song0ch0:
	.byte $46, $03, $ff, $93, $a0
@song0ref6:
	.byte $3a, $81, $00, $81, $39, $81, $00, $81, $35, $81, $00, $81, $30, $81, $00, $81
	.byte $41, $10
	.word @song0ref6
	.byte $41, $10
	.word @song0ref6
	.byte $41, $10
	.word @song0ref6
	.byte $9a, $22, $81, $27, $81, $22, $81, $27, $81, $29, $8d, $00, $9d, $ff, $be, $38, $bd, $38, $85, $00, $87, $7d, $38, $85
	.byte $00, $87, $7b, $38, $85, $00, $87, $79, $38, $85, $00, $87, $77, $38, $85, $00, $87, $75, $38, $85, $00, $87, $73, $38
	.byte $85, $00, $87, $71, $38, $85, $00, $87, $44, $00
@song0ch1:
	.byte $ff, $93, $74, $a0, $29, $81, $00, $85, $3a, $81, $75
@song0ref101:
	.byte $29, $81, $39, $81, $00, $81, $35, $81, $76
@song0ref110:
	.byte $29, $81, $30, $81, $00, $81, $3a, $81, $77
	.byte $41, $08
	.word @song0ref101
	.byte $78
	.byte $41, $08
	.word @song0ref110
	.byte $79
	.byte $41, $08
	.word @song0ref101
	.byte $7a
	.byte $41, $08
	.word @song0ref110
	.byte $7b
	.byte $41, $08
	.word @song0ref101
	.byte $78, $9a, $23, $81, $27, $81, $2a, $81, $2e, $81, $2f
@song0ref149:
	.byte $8d, $00, $9d, $ff, $bf, $bf, $bf, $8f, $44, $00
@song0ch2:
	.byte $ff, $93, $8a, $11, $bd, $1d, $bd, $9a, $2a, $81, $2f, $81, $2e, $81, $31, $81, $33
	.byte $41, $09
	.word @song0ref149
@song0ch3:
	.byte $bc, $24, $ff, $91, $00, $bd, $bf, $bf, $ba, $24, $fd, $93, $00, $a9, $bf, $bf, $8f, $44, $00
@song0ch4:
	.byte $ff, $93, $bf, $bf, $bf, $ff, $bf, $bf, $bf, $8f, $44, $00
@song1ch0:
	.byte $46, $03
@song1ch0loop:
	.byte $7a, $a4, $20, $bd, $22, $bd, $23, $bd, $25, $95, $20, $85, $1e, $85, $23, $85, $22, $85, $1e, $85, $20, $bd, $22, $bd
	.byte $23, $bd, $25, $95, $20, $85, $1e, $85, $23, $85, $22, $85, $1e, $85, $7e
@song1ref43:
	.byte $00, $8d, $92, $2c, $85, $45, $85, $25, $8d, $45, $85, $27, $81, $28, $81, $2a, $81, $00, $81, $2a, $81, $00, $81, $28
	.byte $85, $45, $85, $27, $8b, $45, $23, $8b, $45, $25, $8b, $45, $20
@song1ref80:
	.byte $95, $45, $8d, $80, $2c, $81, $2e, $81, $2f, $81, $00, $81, $2e, $81, $2c, $81, $2e, $81, $00, $81, $2c, $81, $2a, $81
	.byte $2c, $81, $00, $81, $2a, $81, $28, $81, $2a, $81, $00, $81, $28, $81, $27, $81
	.byte $41, $23
	.word @song1ref43
	.byte $2c
	.byte $41, $27
	.word @song1ref80
	.byte $41, $20
	.word @song1ref43
@song1ref130:
	.byte $00, $8d, $2f, $85, $45, $85, $28, $8d, $45, $85, $2a, $81, $2b, $81, $2d, $81, $00, $81, $2d, $81, $00, $81, $2b, $85
	.byte $45, $85, $2a, $8b, $45, $26, $8b, $45, $2d, $81, $00, $81, $2c, $81, $2a, $81, $28, $95, $45, $95, $00, $8d, $23, $8b
	.byte $45, $28, $8b, $45, $2d, $8b, $45, $00, $8d, $98, $2a, $8d, $26, $8d, $23, $8d, $21, $85, $23, $85, $26, $85, $2a, $85
	.byte $2d, $9d
	.byte $41, $4b
	.word @song1ref43
	.byte $41, $23
	.word @song1ref43
	.byte $2c
	.byte $41, $27
	.word @song1ref80
	.byte $41, $20
	.word @song1ref43
	.byte $41, $49
	.word @song1ref130
	.byte $00, $8d, $92
@song1ref223:
	.byte $2a, $85, $45, $85, $23, $8b, $45, $25, $85, $26, $85, $28, $85, $45, $85, $26, $85, $45, $85, $25, $85, $45, $85, $21
	.byte $85, $45, $85, $00, $8d
	.byte $41, $1d
	.word @song1ref223
@song1ref255:
	.byte $2d, $85, $45, $85, $26, $8b, $45, $28, $85, $29, $85, $2b, $85, $45, $85, $29, $85, $45, $85, $28, $85, $45, $85, $24
	.byte $85, $45, $85, $00, $8d
	.byte $41, $1d
	.word @song1ref255
	.byte $41, $1d
	.word @song1ref223
	.byte $41, $1d
	.word @song1ref223
	.byte $41, $1b
	.word @song1ref255
	.byte $29, $8b, $45, $2b, $8b, $45, $2c, $8b, $45, $30, $8b, $45, $2e, $99, $45, $81, $2b, $99, $45, $81
@song1ref316:
	.byte $7d, $2a, $81, $00, $85, $2c, $81, $31, $85, $45, $85, $7b, $31, $85, $45, $85, $79, $31, $85, $45, $85, $77, $31, $85
	.byte $45, $85, $75, $31, $85, $45, $85, $73, $31, $85, $45, $85, $71, $31, $85, $45, $85
	.byte $41, $22
	.word @song1ref316
	.byte $41, $22
	.word @song1ref316
	.byte $41, $22
	.word @song1ref316
	.byte $00, $bd, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $7e, $88, $1c, $93, $00, $1c, $85, $1b, $85, $1c, $85, $19
@song1ref399:
	.byte $85, $1b, $85, $1c, $93, $00, $1c, $85, $1b, $85, $1c, $85, $19, $85, $1b, $85, $1c, $93, $00, $1c, $85, $1b, $85, $1c
	.byte $85, $19, $85, $1b, $85, $1c, $95, $1c, $85, $17, $85, $1c, $85, $1e
	.byte $41, $1e
	.word @song1ref399
	.byte $93, $00, $1c, $85, $1b, $85, $1c, $85, $19, $85, $1b, $85, $1c, $95, $1c, $85, $17, $85, $1c, $85, $1e, $85, $1b
@song1ref463:
	.byte $85
@song1ref464:
	.byte $10, $85, $14, $85, $10, $85, $14, $85, $10, $85, $14, $85, $10, $85, $14, $85, $12, $85, $16, $85, $12, $85, $16, $85
	.byte $12, $85, $16, $85, $12, $85, $16, $85, $14, $85, $17, $85, $14, $85, $17, $85, $14, $85, $17, $85, $14, $85, $17, $85
	.byte $12, $85, $16, $85, $12, $85, $16, $85, $12, $85, $16, $85, $12, $85, $16
	.byte $41, $40
	.word @song1ref463
@song1ref530:
	.byte $85, $0d, $85, $15, $85, $0d, $85, $15, $85, $0d, $85, $15, $85, $0d, $85, $15, $85, $0f, $85, $17, $85, $0f, $85, $17
	.byte $85, $0f, $85, $17, $85, $0f, $85, $17, $85, $10, $85, $18, $85, $10, $85, $18, $85, $10, $85, $18, $85, $10, $85, $18
	.byte $85, $12, $85, $1a, $85, $12, $85, $1a, $85, $12, $85, $1a, $85, $12, $85, $1a, $85, $23, $81, $00, $81, $20, $00, $20
	.byte $00, $20, $81, $00, $81, $20, $00, $20, $00, $20, $00, $20, $00, $20, $83, $00, $20, $81, $00, $81, $20, $00, $20, $00
	.byte $23, $81, $00, $81, $20, $00, $20, $00, $17, $00, $1a, $00, $1e, $81, $00, $81, $23, $81, $00, $81, $26, $81, $00, $81
	.byte $28, $81, $00, $81, $23, $81, $00, $81, $8f, $98, $26, $8d, $23, $8d, $1e, $8d, $1c, $85, $1f, $85, $1e, $85, $26, $85
	.byte $23, $9d, $88
	.byte $41, $3f
	.word @song1ref464
	.byte $41, $40
	.word @song1ref463
	.byte $41, $91
	.word @song1ref530
	.byte $88
@song1ref687:
	.byte $17, $85, $13, $85, $1a, $85, $13, $85, $1e, $85, $13, $85, $17, $85, $13, $85, $15, $85, $12, $85, $1c, $85, $12, $85
	.byte $1e, $85, $12, $85, $19, $85, $12, $85
	.byte $41, $20
	.word @song1ref687
	.byte $1a, $85, $16, $85, $1d, $85, $16, $85, $21, $85, $16, $85, $1a, $85, $16, $85, $18, $85, $15, $85, $1f, $85, $15, $85
	.byte $21, $85, $15, $85, $1c, $85, $15, $85
@song1ref754:
	.byte $1a, $85, $16, $85, $80, $30, $81, $82, $1d, $81, $80, $32, $81, $82, $16, $81, $80, $30, $81, $82, $21, $81, $88, $16
	.byte $85, $80, $2d, $81, $82, $1a, $81, $80, $2e, $81, $82, $16, $81, $80, $30, $81, $82, $18, $81, $88, $15, $85, $80, $2e
	.byte $81, $82, $1f, $81, $80, $2d, $81, $82, $15, $81, $80, $2b, $81, $82, $21, $81, $88, $15, $85, $80, $2d, $81, $82, $1c
	.byte $81, $88, $15, $85
@song1ref830:
	.byte $17, $85, $80, $2a, $81, $82, $13, $81, $80, $2d, $81, $82, $1a, $81, $80, $2f, $81, $82, $13, $81, $80, $26, $81, $82
	.byte $1e, $81, $80, $25, $81, $82, $13, $81, $80, $26, $81, $82, $17, $81, $80, $2f, $81, $82, $13, $81, $80, $2d, $81, $82
	.byte $15, $81, $88, $12, $85, $1c, $85, $12, $85, $1e, $85, $80, $25, $81, $82, $12, $81, $80, $26, $81, $82, $19, $81, $80
	.byte $2d, $81, $82, $12, $81, $88
	.byte $41, $1e
	.word @song1ref830
	.byte $80, $31, $81, $82, $15, $81, $80, $32, $81, $82, $12, $81, $80, $39, $81, $82, $1c, $81, $80, $36, $81, $82, $12, $81
	.byte $80, $34, $81, $82, $1e, $81, $80, $32, $81, $82, $12, $81, $80, $31, $81, $82, $19, $81, $80, $32, $81, $82, $12, $81
	.byte $88
	.byte $41, $34
	.word @song1ref754
	.byte $19, $85, $14, $85, $1b, $85, $18, $85, $1d, $85, $19, $85, $20, $85, $1d, $85, $1f, $85, $1d, $85, $1b, $85, $18, $85
	.byte $16, $85, $18, $85, $1b, $85, $1f, $85, $7f
@song1ref996:
	.byte $1d, $85, $1e, $85, $7d, $1d, $85, $1e, $85, $7b, $1d, $85, $1e, $85, $79, $1d, $85, $1e, $85, $77, $1d, $85, $1e, $85
	.byte $75, $1d, $85, $1e, $85, $73, $1d, $85, $1e, $85, $71, $1d, $85, $1e, $85, $7f, $20, $85, $21, $85, $7d, $20, $85, $21
	.byte $85, $7b, $20, $85, $21, $85, $79, $20, $85, $21, $85, $77, $20, $85, $21, $85, $75, $20, $85, $21, $85, $73, $20, $85
	.byte $21, $85, $71, $20, $85, $21, $85, $7f, $a2
	.byte $41, $20
	.word @song1ref996
	.byte $7f, $1b, $85, $1c, $85, $7d, $1b, $85, $1c, $85, $7b, $1b, $85, $1c, $85, $79, $1b, $85, $1c, $85, $77, $19, $85, $1a
	.byte $85, $75, $19, $85, $1a, $85, $73, $17, $85, $18, $85, $71, $17, $85, $18, $85, $00, $bd, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $8a
@song1ref1142:
	.byte $19, $83, $00, $19, $00, $19, $00, $19, $83, $00, $19, $00, $19, $00, $19, $00, $19, $00, $19, $83, $00, $19, $81, $17
	.byte $87, $00, $19, $83, $00, $19, $00, $19, $00, $19, $83, $00, $19, $00, $19, $00, $19, $00, $19, $00, $19, $83, $00, $19
	.byte $81, $17, $87, $00
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
@song1ref1215:
	.byte $15, $83, $00, $21, $00, $15, $00, $15, $83, $00, $15, $00, $15, $00, $15, $00, $15, $00, $15, $83, $00, $15, $81, $00
	.byte $81, $15, $85, $17, $83, $00, $23, $00, $17, $00, $17, $83, $00, $17, $00, $17, $00, $17, $00, $17, $00, $17, $83, $00
	.byte $17, $81, $00, $81, $17, $85, $18, $83, $00, $24, $00, $18, $00, $18, $83, $00, $18, $00, $18, $00, $18, $00, $18, $00
	.byte $18, $83, $00, $18, $81, $00, $81, $18, $85, $1a, $83, $00, $26, $00, $1a, $00, $1a, $83, $00, $1a, $00, $1a, $00, $1a
	.byte $00, $1a, $00, $1a, $83, $00, $1a, $81, $00, $81, $1a
@song1ref1322:
	.byte $85, $1c, $83, $00, $28, $81, $20, $81, $1c, $83, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $00, $1c, $83, $00, $1c, $81
	.byte $00, $81, $1c
	.byte $41, $1b
	.word @song1ref1322
	.byte $85, $17, $bd, $0b, $bd
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $86
	.word @song1ref1215
	.byte $41, $1b
	.word @song1ref1322
	.byte $85, $17, $bd, $0b, $bd
@song1ref1380:
	.byte $13, $83, $00, $13, $00, $13, $00, $13, $83, $00, $13, $00, $13, $00, $13, $00, $13, $00, $13, $83, $00, $1a, $85, $13
	.byte $85, $12, $83, $00, $12, $00, $12, $00, $12, $83, $00, $12, $00, $12, $00, $12, $00, $12, $00, $12, $83, $00, $19, $85
	.byte $12, $85
	.byte $41, $32
	.word @song1ref1380
@song1ref1433:
	.byte $16, $83, $00, $16, $00, $16, $00, $16, $83, $00, $16, $00, $16, $00, $16, $00, $16, $00, $16, $83, $00, $1d, $85, $16
	.byte $85, $15, $83, $00, $15, $00, $15, $00, $15, $83, $00, $15, $00, $15, $00, $15, $00, $15, $00, $15, $83, $00, $1c, $85
	.byte $15, $85
	.byte $41, $32
	.word @song1ref1433
	.byte $41, $32
	.word @song1ref1380
	.byte $41, $32
	.word @song1ref1380
	.byte $41, $32
	.word @song1ref1433
	.byte $19, $83, $00, $19, $00, $19, $00, $19, $83, $00, $19, $00, $19, $00, $19, $00, $19, $00, $19, $83, $00, $20, $85, $19
	.byte $85, $18, $83, $00, $18, $00, $18, $00, $18, $83, $00, $18, $00, $18, $00, $18, $00, $18, $00, $18, $83, $00, $1f, $85
	.byte $18, $85, $12, $bd, $bf, $10, $bd, $bf, $12, $bd, $bf, $10, $bd, $0e, $9d, $0c, $9d, $00, $bd, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $bf, $bf, $bf, $bf
	.byte $41, $34
	.word @song1ref1142
	.byte $41, $34
	.word @song1ref1142
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $7a
@song1ref1584:
	.byte $8c
@song1ref1585:
	.byte $2c, $85, $72, $2c, $81, $2c, $81, $7a, $2c, $85, $72, $2c, $81, $2c, $81, $7a, $2c, $85, $75, $2c, $81, $77, $2c, $81
	.byte $7a, $2c, $85, $72, $2c, $85, $7a, $2c, $85, $72, $2c, $81, $2c, $81, $7a, $2c, $85, $72, $2c, $81, $2c, $81, $7a, $2c
	.byte $85, $75, $2c, $81, $77, $2c, $81, $7a, $2c, $85, $72, $2c, $85, $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $00, $bd, $bf, $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $00, $bd, $bf, $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $00, $bd, $bf, $bf, $bf, $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a, $a6, $2c, $bd, $8f, $00, $ad, $2a, $bd, $8f, $00, $ad, $2c, $bd, $8f, $00, $ad, $2a, $bd, $8f, $00, $ad
	.byte $41, $2c
	.word @song1ref1584
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $7a
	.byte $41, $2c
	.word @song1ref1585
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref1806:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $bf
	.byte $41, $1b
	.word @song1ref1806
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $42
	.word @song1ch4loop
@song2ch0:
	.byte $46, $03
@song2ch0loop:
	.byte $7a, $a4, $1e, $bd, $20, $bd, $21, $bd, $23, $95, $1e, $85, $1c, $85, $21, $85, $20, $85, $1c, $85, $1e, $bd, $20, $bd
	.byte $21, $bd, $23, $95, $1e, $85, $1c, $85, $21, $85, $20, $85, $1c, $85, $7e
@song2ref43:
	.byte $00, $8d, $92, $2a, $85, $45, $85, $23, $8d, $45, $85, $25, $81, $26, $81, $28, $81, $00, $81, $28, $81, $00, $81, $26
	.byte $85, $45, $85, $25, $8b, $45, $21, $8b, $45, $23, $8b, $45, $1e
@song2ref80:
	.byte $95, $45, $8d, $80, $2a, $81, $2c, $81, $2d, $81, $00, $81, $2c, $81, $2a, $81, $2c, $81, $00, $81, $2a, $81, $28, $81
	.byte $2a, $81, $00, $81, $28, $81, $26, $81, $28, $81, $00, $81, $26, $81, $25, $81
	.byte $41, $23
	.word @song2ref43
	.byte $2a
	.byte $41, $27
	.word @song2ref80
	.byte $41, $20
	.word @song2ref43
@song2ref130:
	.byte $00, $8d, $2d, $85, $45, $85, $26, $8d, $45, $85, $28, $81, $29, $81, $2b, $81, $00, $81, $2b, $81, $00, $81, $29, $85
	.byte $45, $85, $28, $8b, $45, $24, $8b, $45, $2b, $81, $00, $81, $2a, $81, $28, $81, $26, $95, $45, $95, $00, $8d, $21, $8b
	.byte $45, $26, $8b, $45, $2b, $8b, $45, $00, $8d, $98, $28, $8d, $24, $8d, $21, $8d, $1f, $85, $21, $85, $24, $85, $28, $85
	.byte $2b, $9d
	.byte $41, $4b
	.word @song2ref43
	.byte $41, $23
	.word @song2ref43
	.byte $2a
	.byte $41, $27
	.word @song2ref80
	.byte $41, $20
	.word @song2ref43
	.byte $41, $49
	.word @song2ref130
	.byte $00, $8d, $92
@song2ref223:
	.byte $28, $85, $45, $85, $21, $8b, $45, $23, $85, $24, $85, $26, $85, $45, $85, $24, $85, $45, $85, $23, $85, $45, $85, $1f
	.byte $85, $45, $85, $00, $8d
	.byte $41, $1d
	.word @song2ref223
@song2ref255:
	.byte $2b, $85, $45, $85, $24, $8b, $45, $26, $85, $27, $85, $29, $85, $45, $85, $27, $85, $45, $85, $26, $85, $45, $85, $22
	.byte $85, $45, $85, $00, $8d
	.byte $41, $1d
	.word @song2ref255
	.byte $41, $1d
	.word @song2ref223
	.byte $41, $1d
	.word @song2ref223
	.byte $41, $1b
	.word @song2ref255
	.byte $27, $8b, $45, $29, $8b, $45, $2a, $8b, $45, $2e, $8b, $45, $2c, $99, $45, $81, $29, $99, $45, $81
@song2ref316:
	.byte $7d, $28, $81, $00, $85, $2a, $81, $2f, $85, $45, $85, $7b, $2f, $85, $45, $85, $79, $2f, $85, $45, $85, $77, $2f, $85
	.byte $45, $85, $75, $2f, $85, $45, $85, $73, $2f, $85, $45, $85, $71, $2f, $85, $45, $85
	.byte $41, $22
	.word @song2ref316
	.byte $41, $22
	.word @song2ref316
	.byte $41, $22
	.word @song2ref316
	.byte $00, $bd, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $7e, $88, $1a, $93, $00, $1a, $85, $19, $85, $1a, $85, $17
@song2ref399:
	.byte $85, $19, $85, $1a, $93, $00, $1a, $85, $19, $85, $1a, $85, $17, $85, $19, $85, $1a, $93, $00, $1a, $85, $19, $85, $1a
	.byte $85, $17, $85, $19, $85, $1a, $95, $1a, $85, $15, $85, $1a, $85, $1c
	.byte $41, $1e
	.word @song2ref399
	.byte $93, $00, $1a, $85, $19, $85, $1a, $85, $17, $85, $19, $85, $1a, $95, $1a, $85, $15, $85, $1a, $85, $1c, $85, $19
@song2ref463:
	.byte $85
@song2ref464:
	.byte $0e, $85, $12, $85, $0e, $85, $12, $85, $0e, $85, $12, $85, $0e, $85, $12, $85, $10, $85, $14, $85, $10, $85, $14, $85
	.byte $10, $85, $14, $85, $10, $85, $14, $85, $12, $85, $15, $85, $12, $85, $15, $85, $12, $85, $15, $85, $12, $85, $15, $85
	.byte $10, $85, $14, $85, $10, $85, $14, $85, $10, $85, $14, $85, $10, $85, $14
	.byte $41, $40
	.word @song2ref463
@song2ref530:
	.byte $85, $0b, $85, $13, $85, $0b, $85, $13, $85, $0b, $85, $13, $85, $0b, $85, $13, $85, $0d, $85, $15, $85, $0d, $85, $15
	.byte $85, $0d, $85, $15, $85, $0d, $85, $15, $85, $0e, $85, $16, $85, $0e, $85, $16, $85, $0e, $85, $16, $85, $0e, $85, $16
	.byte $85, $10, $85, $18, $85, $10, $85, $18, $85, $10, $85, $18, $85, $10, $85, $18, $85, $21, $81, $00, $81, $1e, $00, $1e
	.byte $00, $1e, $81, $00, $81, $1e, $00, $1e, $00, $1e, $00, $1e, $00, $1e, $83, $00, $1e, $81, $00, $81, $1e, $00, $1e, $00
	.byte $21, $81, $00, $81, $1e, $00, $1e, $00, $15, $00, $18, $00, $1c, $81, $00, $81, $21, $81, $00, $81, $24, $81, $00, $81
	.byte $26, $81, $00, $81, $21, $81, $00, $81, $8f, $98, $24, $8d, $21, $8d, $1c, $8d, $1a, $85, $1d, $85, $1c, $85, $24, $85
	.byte $21, $9d, $88
	.byte $41, $3f
	.word @song2ref464
	.byte $41, $40
	.word @song2ref463
	.byte $41, $91
	.word @song2ref530
	.byte $88
@song2ref687:
	.byte $15, $85, $11, $85, $18, $85, $11, $85, $1c, $85, $11, $85, $15, $85, $11, $85, $13, $85, $10, $85, $1a, $85, $10, $85
	.byte $1c, $85, $10, $85, $17, $85, $10, $85
	.byte $41, $20
	.word @song2ref687
	.byte $18, $85, $14, $85, $1b, $85, $14, $85, $1f, $85, $14, $85, $18, $85, $14, $85, $16, $85, $13, $85, $1d, $85, $13, $85
	.byte $1f, $85, $13, $85, $1a, $85, $13, $85
@song2ref754:
	.byte $18, $85, $14, $85, $80, $2e, $81, $82, $1b, $81, $80, $30, $81, $82, $14, $81, $80, $2e, $81, $82, $1f, $81, $88, $14
	.byte $85, $80, $2b, $81, $82, $18, $81, $80, $2c, $81, $82, $14, $81, $80, $2e, $81, $82, $16, $81, $88, $13, $85, $80, $2c
	.byte $81, $82, $1d, $81, $80, $2b, $81, $82, $13, $81, $80, $29, $81, $82, $1f, $81, $88, $13, $85, $80, $2b, $81, $82, $1a
	.byte $81, $88, $13, $85
@song2ref830:
	.byte $15, $85, $80, $28, $81, $82, $11, $81, $80, $2b, $81, $82, $18, $81, $80, $2d, $81, $82, $11, $81, $80, $24, $81, $82
	.byte $1c, $81, $80, $23, $81, $82, $11, $81, $80, $24, $81, $82, $15, $81, $80, $2d, $81, $82, $11, $81, $80, $2b, $81, $82
	.byte $13, $81, $88, $10, $85, $1a, $85, $10, $85, $1c, $85, $80, $23, $81, $82, $10, $81, $80, $24, $81, $82, $17, $81, $80
	.byte $2b, $81, $82, $10, $81, $88
	.byte $41, $1e
	.word @song2ref830
	.byte $80, $2f, $81, $82, $13, $81, $80, $30, $81, $82, $10, $81, $80, $37, $81, $82, $1a, $81, $80, $34, $81, $82, $10, $81
	.byte $80, $32, $81, $82, $1c, $81, $80, $30, $81, $82, $10, $81, $80, $2f, $81, $82, $17, $81, $80, $30, $81, $82, $10, $81
	.byte $88
	.byte $41, $34
	.word @song2ref754
	.byte $17, $85, $12, $85, $19, $85, $16, $85, $1b, $85, $17, $85, $1e, $85, $1b, $85, $1d, $85, $1b, $85, $19, $85, $16, $85
	.byte $14, $85, $16, $85, $19, $85, $1d, $85, $7f
@song2ref996:
	.byte $1b, $85, $1c, $85, $7d, $1b, $85, $1c, $85, $7b, $1b, $85, $1c, $85, $79, $1b, $85, $1c, $85, $77, $1b, $85, $1c, $85
	.byte $75, $1b, $85, $1c, $85, $73, $1b, $85, $1c, $85, $71, $1b, $85, $1c, $85, $7f, $1e, $85, $1f, $85, $7d, $1e, $85, $1f
	.byte $85, $7b, $1e, $85, $1f, $85, $79, $1e, $85, $1f, $85, $77, $1e, $85, $1f, $85, $75, $1e, $85, $1f, $85, $73, $1e, $85
	.byte $1f, $85, $71, $1e, $85, $1f, $85, $7f, $a2
	.byte $41, $20
	.word @song2ref996
	.byte $7f, $19, $85, $1a, $85, $7d, $19, $85, $1a, $85, $7b, $19, $85, $1a, $85, $79, $19, $85, $1a, $85, $77, $17, $85, $18
	.byte $85, $75, $17, $85, $18, $85, $73, $15, $85, $16, $85, $71, $15, $85, $16, $85, $00, $bd, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $8a
@song2ref1142:
	.byte $17, $83, $00, $17, $00, $17, $00, $17, $83, $00, $17, $00, $17, $00, $17, $00, $17, $00, $17, $83, $00, $17, $81, $15
	.byte $87, $00, $17, $83, $00, $17, $00, $17, $00, $17, $83, $00, $17, $00, $17, $00, $17, $00, $17, $00, $17, $83, $00, $17
	.byte $81, $15, $87, $00
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
@song2ref1215:
	.byte $13, $83, $00, $1f, $00, $13, $00, $13, $83, $00, $13, $00, $13, $00, $13, $00, $13, $00, $13, $83, $00, $13, $81, $00
	.byte $81, $13, $85, $15, $83, $00, $21, $00, $15, $00, $15, $83, $00, $15, $00, $15, $00, $15, $00, $15, $00, $15, $83, $00
	.byte $15, $81, $00, $81, $15, $85, $16, $83, $00, $22, $00, $16, $00, $16, $83, $00, $16, $00, $16, $00, $16, $00, $16, $00
	.byte $16, $83, $00, $16, $81, $00, $81, $16, $85, $18, $83, $00, $24, $00, $18, $00, $18, $83, $00, $18, $00, $18, $00, $18
	.byte $00, $18, $00, $18, $83, $00, $18, $81, $00, $81, $18
@song2ref1322:
	.byte $85, $1a, $83, $00, $26, $81, $1e, $81, $1a, $83, $00, $1a, $00, $1a, $00, $1a, $00, $1a, $00, $1a, $83, $00, $1a, $81
	.byte $00, $81, $1a
	.byte $41, $1b
	.word @song2ref1322
	.byte $85, $15, $bd, $09, $bd
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $86
	.word @song2ref1215
	.byte $41, $1b
	.word @song2ref1322
	.byte $85, $15, $bd, $09, $bd
@song2ref1380:
	.byte $11, $83, $00, $11, $00, $11, $00, $11, $83, $00, $11, $00, $11, $00, $11, $00, $11, $00, $11, $83, $00, $18, $85, $11
	.byte $85, $10, $83, $00, $10, $00, $10, $00, $10, $83, $00, $10, $00, $10, $00, $10, $00, $10, $00, $10, $83, $00, $17, $85
	.byte $10, $85
	.byte $41, $32
	.word @song2ref1380
@song2ref1433:
	.byte $14, $83, $00, $14, $00, $14, $00, $14, $83, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $83, $00, $1b, $85, $14
	.byte $85, $13, $83, $00, $13, $00, $13, $00, $13, $83, $00, $13, $00, $13, $00, $13, $00, $13, $00, $13, $83, $00, $1a, $85
	.byte $13, $85
	.byte $41, $32
	.word @song2ref1433
	.byte $41, $32
	.word @song2ref1380
	.byte $41, $32
	.word @song2ref1380
	.byte $41, $32
	.word @song2ref1433
	.byte $17, $83, $00, $17, $00, $17, $00, $17, $83, $00, $17, $00, $17, $00, $17, $00, $17, $00, $17, $83, $00, $1e, $85, $17
	.byte $85, $16, $83, $00, $16, $00, $16, $00, $16, $83, $00, $16, $00, $16, $00, $16, $00, $16, $00, $16, $83, $00, $1d, $85
	.byte $16, $85, $10, $bd, $bf, $0e, $bd, $bf, $10, $bd, $bf, $0e, $bd, $0c, $9d, $0a, $9d, $00, $bd, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $bf, $bf, $bf, $bf
	.byte $41, $34
	.word @song2ref1142
	.byte $41, $34
	.word @song2ref1142
	.byte $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $7a
@song2ref1584:
	.byte $8c
@song2ref1585:
	.byte $2a, $85, $72, $2a, $81, $2a, $81, $7a, $2a, $85, $72, $2a, $81, $2a, $81, $7a, $2a, $85, $75, $2a, $81, $77, $2a, $81
	.byte $7a, $2a, $85, $72, $2a, $85, $7a, $2a, $85, $72, $2a, $81, $2a, $81, $7a, $2a, $85, $72, $2a, $81, $2a, $81, $7a, $2a
	.byte $85, $75, $2a, $81, $77, $2a, $81, $7a, $2a, $85, $72, $2a, $85, $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $00, $bd, $bf, $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $00, $bd, $bf, $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $00, $bd, $bf, $bf, $bf, $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a, $a6, $2b, $bd, $8f, $00, $ad, $29, $bd, $8f, $00, $ad, $2b, $bd, $8f, $00, $ad, $29, $bd, $8f, $00, $ad
	.byte $41, $2c
	.word @song2ref1584
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $7a
	.byte $41, $2c
	.word @song2ref1585
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
@song2ref1806:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $bf
	.byte $41, $1b
	.word @song2ref1806
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $bf, $bf, $42
	.word @song2ch4loop
@song3ch0:
	.byte $46, $03
@song3ch0loop:
	.byte $7f, $b8, $36, $91, $75, $26
@song3ref10:
	.byte $87, $7a, $36, $87, $7f, $2b, $87, $7a, $89, $75, $36, $87, $7a, $2b, $87, $7f, $2f, $91, $75, $2b, $87, $7a, $2f, $87
	.byte $7f, $2b, $91, $75, $2f, $87, $7a, $2b, $87, $7f, $36, $91, $75, $2b
	.byte $41, $16
	.word @song3ref10
	.byte $7f, $32, $91, $75, $2b, $87, $7a, $32, $87, $7f, $28, $87, $7a, $89, $75, $32, $87, $7a, $28, $87, $7f, $2b, $91, $75
	.byte $28, $87, $7a, $2b, $87, $7f, $28, $91, $75, $2b, $87, $7a, $28, $87, $7f, $32, $91, $75, $28, $87, $7a, $32, $87, $7f
	.byte $2b, $87, $7a, $89, $75, $32, $87, $7a, $2b, $87, $7f, $2a, $91, $75, $2b, $87, $7a, $2a, $87, $7f, $26, $91, $75, $2a
	.byte $87, $7a, $26, $87, $42
	.word @song3ch0loop
@song3ch4:
@song3ch3:
@song3ch1:
@song3ch1loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $8a, $28, $91, $00, $ff, $89, $28, $91, $00, $ff, $89, $24, $91, $00, $ff, $89, $24, $91, $00, $ff, $89, $42
	.word @song3ch2loop
@song4ch0:
	.byte $46, $09
@song4ch0loop:
	.byte $7f, $ac, $23, $91, $75, $13
@song4ref10:
	.byte $87, $7a, $23, $87, $7f, $18, $87, $7a, $89, $75, $23, $87, $7a, $18, $87, $7f, $1c, $91, $75, $18, $87, $7a, $1c, $87
	.byte $7f, $18, $91, $75, $1c, $87, $7a, $18, $87, $7f, $23, $91, $75, $18
	.byte $41, $16
	.word @song4ref10
	.byte $7f, $1f, $91, $75, $18, $87, $7a, $1f, $87, $7f, $15, $87, $7a, $89, $75, $1f, $87, $7a, $15, $87, $7f, $18, $91, $75
	.byte $15, $87, $7a, $18, $87, $7f, $15, $91, $75, $18, $87, $7a, $15, $87, $7f, $1f, $91, $75, $15, $87, $7a, $1f, $87, $7f
	.byte $18, $87, $7a, $89, $75, $1f, $87, $7a, $18, $87, $7f, $17, $91, $75, $18, $87, $7a, $17, $87, $7f, $13, $91, $75, $17
	.byte $87, $7a, $13, $87, $42
	.word @song4ch0loop
@song4ch4:
@song4ch3:
@song4ch1:
@song4ch1loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $8a, $15, $91, $00, $ff, $89, $15, $91, $00, $ff, $89, $11, $91, $00, $ff, $89, $11, $91, $00, $ff, $89, $42
	.word @song4ch2loop
@song5ch0:
	.byte $46, $05, $76
@song5ref4:
	.byte $9e
@song5ref5:
	.byte $08, $85, $0f, $85, $0d, $85, $0f, $85, $08, $85, $0f, $85, $0d, $85, $0f, $85
@song5ch0loop:
@song5ref22:
	.byte $78
@song5ref23:
	.byte $06, $85, $0f
@song5ref26:
	.byte $85, $0d, $85, $0f, $85, $06, $85, $0f, $85, $0d, $85, $0f, $85, $79, $04
@song5ref41:
	.byte $85, $0f, $85, $0d, $85, $0f, $85, $04, $85, $0f, $85, $0d, $85, $0f, $85, $7a
@song5ref57:
	.byte $03, $85, $0f, $85, $0d, $85, $0f, $85, $14, $85, $0f, $85, $0d, $85, $0f, $85, $7c
@song5ref74:
	.byte $01, $85, $12, $85, $10, $85, $12, $85, $08, $85, $12, $85, $10, $85, $12, $85, $7d, $0b, $85, $10, $85, $0f, $85, $10
	.byte $85, $06, $85, $10, $85, $0f, $85, $10, $85, $7f
@song5ref108:
	.byte $0a
@song5ref109:
	.byte $85
@song5ref110:
	.byte $10, $85, $0d
@song5ref113:
	.byte $85, $10, $85, $0a, $85, $10, $85, $0d, $85, $10, $85, $7d
@song5ref125:
	.byte $0a, $85, $10, $85, $0d, $85, $10, $85, $08, $85, $10, $85, $0d, $85, $10, $85, $7b, $07, $85, $10, $85, $0d, $85, $10
	.byte $85, $04, $85, $10, $85, $0d, $85, $10, $85, $78
@song5ref159:
	.byte $03, $85, $07, $85, $0f, $85, $0a, $85, $07, $85, $0a, $85, $0f, $85, $13, $85, $76
	.byte $41, $10
	.word @song5ref5
	.byte $41, $90
	.word @song5ref22
	.byte $76
@song5ref183:
	.byte $0d, $85, $12, $85, $10, $85, $12, $85, $0d, $85, $12, $85, $10, $85, $12, $85, $78
@song5ref200:
	.byte $0b, $85, $10, $85, $0f, $85, $10, $85, $0b, $85, $10, $85, $0f, $85, $10, $85, $7a
@song5ref217:
	.byte $09, $85
@song5ref219:
	.byte $10, $85
@song5ref221:
	.byte $0d, $85, $10, $85, $09, $85, $10, $85, $0d, $85, $10, $85
	.byte $41, $10
	.word @song5ref217
	.byte $7c
	.byte $41, $10
	.word @song5ref108
	.byte $7f
	.byte $41, $28
	.word @song5ref125
	.byte $0f, $85, $0a, $85, $0f, $85, $13, $85, $76
	.byte $41, $10
	.word @song5ref5
	.byte $42
	.word @song5ch0loop
@song5ch1:
	.byte $72, $95
	.byte $41, $0b
	.word @song5ref4
@song5ch1loop:
	.byte $41, $0d
	.word @song5ref26
	.byte $06
	.byte $41, $0f
	.word @song5ref41
	.byte $04, $85, $73, $0f, $85, $0d, $85, $0f, $85
	.byte $41, $10
	.word @song5ref57
	.byte $41, $0c
	.word @song5ref74
@song5ref287:
	.byte $71, $10, $85, $73, $12, $85, $0b, $85, $10, $85, $0f, $85, $10, $85, $06, $85, $74, $10, $85, $0f
	.byte $41, $0b
	.word @song5ref113
	.byte $41, $10
	.word @song5ref108
@song5ref313:
	.byte $08, $85, $73, $10, $85, $0d, $85, $10, $85, $07, $85, $10, $85, $0d, $85, $10, $85, $04, $85, $72, $10, $85, $0d, $85
	.byte $10, $85
	.byte $41, $0c
	.word @song5ref159
	.byte $71, $0f, $85, $13, $72, $85
	.byte $41, $10
	.word @song5ref5
	.byte $41, $10
	.word @song5ref23
	.byte $04, $85, $0f, $85, $0d, $85, $0f, $85, $04, $85, $73, $0f, $85, $0d, $85, $0f, $85
	.byte $41, $10
	.word @song5ref57
	.byte $41, $0c
	.word @song5ref74
	.byte $41, $11
	.word @song5ref287
	.byte $41, $0b
	.word @song5ref113
	.byte $41, $10
	.word @song5ref108
	.byte $41, $18
	.word @song5ref313
	.byte $41, $10
	.word @song5ref159
	.byte $41, $10
	.word @song5ref183
	.byte $41, $0c
	.word @song5ref200
	.byte $41, $0c
	.word @song5ref221
	.byte $09, $85, $73
	.byte $41, $0e
	.word @song5ref219
	.byte $09
	.byte $41, $0f
	.word @song5ref109
	.byte $0a, $85, $74
	.byte $41, $0e
	.word @song5ref110
	.byte $41, $18
	.word @song5ref313
	.byte $03, $85, $07, $85, $0f, $85, $0a, $85, $0f, $85, $0a, $85, $0f, $85, $00, $13, $83
	.byte $41, $0b
	.word @song5ref5
	.byte $42
	.word @song5ch1loop
@song5ch4:
@song5ch3:
@song5ch2:
	.byte $bf
@song5ch2loop:
@song5ref447:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $41, $0b
	.word @song5ref447
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $42
	.word @song5ch2loop
@song6ch0:
	.byte $46, $0a
@song6ch0loop:
	.byte $7a, $49, .lobyte(@env4), .hibyte(@env4), $b4, $04, $81, $b4, $03, $81, $40, $0c, $81, $01, $81
@song6ref19:
	.byte $49, .lobyte(@env42), .hibyte(@env42), $07
@song6ref23:
	.byte $cd, $49, .lobyte(@env4), .hibyte(@env4), $04, $81, $b4, $03, $81, $40, $0c, $81, $01, $81, $49, .lobyte(@env42), .hibyte(@env42)
	.byte $0b
	.byte $41, $09
	.word @song6ref23
	.byte $41, $0b
	.word @song6ref19
	.byte $cd, $78, $b4
@song6ref50:
	.byte $04, $81, $03, $81, $40, $0c, $81, $01, $a1, $00, $8d
	.byte $41, $0a
	.word @song6ref50
	.byte $41, $0a
	.word @song6ref50
	.byte $bf, $bf, $bf, $9f, $42
	.word @song6ch0loop
@song6ch1:
@song6ch1loop:
	.byte $df, $df, $df, $df, $bf, $bf, $bf, $bf, $bf, $bf, $9f, $42
	.word @song6ch1loop
@song6ch2:
@song6ch2loop:
	.byte $49, .lobyte(@env4), .hibyte(@env4), $8a
@song6ref94:
	.byte $10, $81, $8a, $0f, $81, $0c, $81, $0d, $81, $49, .lobyte(@env42), .hibyte(@env42), $cf, $49, .lobyte(@env4), .hibyte(@env4)
	.byte $41, $09
	.word @song6ref94
	.byte $49, .lobyte(@env4), .hibyte(@env4)
	.byte $41, $09
	.word @song6ref94
	.byte $49, .lobyte(@env4), .hibyte(@env4)
	.byte $41, $09
	.word @song6ref94
@song6ref125:
	.byte $49, .lobyte(@env48), .hibyte(@env48), $10, $81, $8a, $0f, $81, $0c, $81, $0d, $81, $49, .lobyte(@env42), .hibyte(@env42)
	.byte $9f, $8a, $07, $8d
	.byte $41, $0b
	.word @song6ref125
	.byte $41, $0b
	.word @song6ref125
	.byte $af, $00, $8d, $bf, $bf, $9f, $42
	.word @song6ch2loop
@song6ch3:
@song6ch3loop:
	.byte $df, $df, $df, $df, $78, $8f, $b2, $26, $9d, $25, $8d, $8f, $26, $9d, $25, $8d, $8f, $27, $9d, $25, $8d, $8f, $77, $24
	.byte $9d, $25, $85, $75, $87, $8f, $73, $24, $9d, $25, $85, $72, $87, $8f, $71, $24, $ad, $00, $9d, $42
	.word @song6ch3loop
@song6ch4:
@song6ch4loop:
	.byte $52, $80, $af, $52, $c5, $af, $52, $80, $af, $52, $c5, $af, $52, $80, $af, $52, $c5, $af, $52, $80, $af, $52, $c5, $af
	.byte $52, $80, $bf, $bf, $bf, $bf, $bf, $bf, $9f, $42
	.word @song6ch4loop
@song7ch0:
	.byte $46, $04
@song7ch0loop:
	.byte $bf, $bf, $42
	.word @song7ch0loop
@song7ch4:
@song7ch3:
@song7ch1:
@song7ch1loop:
	.byte $bf, $bf, $42
	.word @song7ch1loop
@song7ch2:
@song7ch2loop:
	.byte $b0
@song7ref19:
	.byte $17, $16, $17, $16, $17, $16, $17, $16, $17, $16, $17, $16, $17, $16, $17, $16
	.byte $41, $10
	.word @song7ref19
@song7ref38:
	.byte $15, $16, $15, $16, $15, $16, $15, $16, $15, $16, $15, $16, $15, $16, $15, $16
	.byte $41, $10
	.word @song7ref38
	.byte $42
	.word @song7ch2loop
@song8ch0:
	.byte $46, $03
@song8ch0loop:
	.byte $75, $4e, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a, $8a
@song8ref12:
	.byte $11, $00, $11, $00, $11, $00, $11, $00, $11, $00, $11, $00, $11, $00, $11, $00, $12, $00, $12, $00, $12, $00, $12, $00
	.byte $12, $00, $12, $00, $12, $00, $12, $00, $4e, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $20
	.word @song8ref12
	.byte $4e, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $20
	.word @song8ref12
	.byte $11, $00, $11, $00, $11, $00, $11, $00, $11, $00, $11, $00, $11, $00, $11, $00, $12, $00, $12, $00, $12, $00, $12, $00
	.byte $12, $00, $12, $00, $81, $78, $ae, $2e, $31, $33, $7c
@song8ref97:
	.byte $38, $81, $38, $85, $7a, $38, $85, $78, $38, $85, $76, $38, $81, $7c, $38, $85, $7a, $38, $85, $78, $38, $85, $76, $38
	.byte $85, $74, $38, $85, $72, $38, $85, $00, $a7, $78, $2e, $31, $33, $7c, $38, $81, $38, $85, $7a, $38, $85, $78, $38, $85
	.byte $76, $38, $81, $7c, $38, $85, $7a, $38, $85, $78, $38, $85, $76, $38, $85, $7c, $38, $85, $38, $81, $3a, $85, $3a, $81
	.byte $33, $85, $33, $81, $35, $85, $35, $81, $31, $85, $33, $85
	.byte $41, $41
	.word @song8ref97
	.byte $78, $c0, $29, $bd, $af, $25, $83, $29, $83, $25, $81, $28, $bd, $bf, $27, $bd, $25, $ad, $20, $81, $21, $81, $00, $85
	.byte $22, $bd, $bf, $29, $bd, $af, $25, $83, $29, $83, $25, $81, $28, $bd, $bf, $27, $bd, $25, $ad, $20, $81, $21, $81, $00
	.byte $85, $22, $bd, $bf, $7a
@song8ref237:
	.byte $4e, $00, $49, .lobyte(@env0), .hibyte(@env0), $4a, $aa, $1b, $85, $00, $81, $78, $49, .lobyte(@env25), .hibyte(@env25)
	.byte $1b, $85, $00, $81, $76, $49, .lobyte(@env23), .hibyte(@env23), $1b, $85, $00, $81, $74, $49, .lobyte(@env56), .hibyte(@env56)
	.byte $1b, $85, $00, $81, $72, $49, .lobyte(@env19), .hibyte(@env19), $1b, $85, $00, $85, $7a, $4e, $00, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $aa, $1b, $85, $00, $81, $78, $49, .lobyte(@env25), .hibyte(@env25), $1b, $85, $00, $81, $76, $49
	.byte .lobyte(@env23), .hibyte(@env23), $1b, $85, $00, $81, $74, $49, .lobyte(@env56), .hibyte(@env56), $1b, $85, $00, $81
	.byte $72, $49, .lobyte(@env19), .hibyte(@env19), $1b, $85, $00, $85, $7a, $4e, $00, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a, $aa, $1b, $85, $00, $81, $78, $49, .lobyte(@env25), .hibyte(@env25), $1b, $85, $00, $81, $76, $49, .lobyte(@env23)
	.byte .hibyte(@env23), $1b, $85, $00, $81, $74, $49, .lobyte(@env56), .hibyte(@env56), $1b, $85, $00, $81, $72, $49, .lobyte(@env19)
	.byte .hibyte(@env19), $1b, $85, $00, $85, $7a, $49, .lobyte(@env0), .hibyte(@env0), $4a, $aa, $1b, $85, $00, $81, $78, $49
	.byte .lobyte(@env25), .hibyte(@env25), $1b, $85, $00, $81, $76, $49, .lobyte(@env23), .hibyte(@env23), $1b, $85, $00, $81
	.byte $74, $49, .lobyte(@env56), .hibyte(@env56), $1b, $85, $00, $81, $78, $4e, $fe, $49, .lobyte(@env19), .hibyte(@env19)
	.byte $1b, $85, $7a, $4e, $fc, $49, .lobyte(@env26), .hibyte(@env26), $1b, $85
	.byte $41, $50
	.word @song8ref237
	.byte $00, $bd, $bf, $bf, $bf, $42
	.word @song8ch0loop
@song8ch1:
@song8ch1loop:
	.byte $47, $00, $7f
@song8ref433:
	.byte $84
@song8ref434:
	.byte $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47
	.byte $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00
	.byte $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a
	.byte $00, $47, $00, $40, $0a, $00, $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
@song8ref609:
	.byte $40, $0a, $86, $38, $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $38, $47, $00, $84
	.byte $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $38, $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a
	.byte $00, $47, $00, $40, $0a, $86, $38, $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $38
	.byte $47, $00, $84, $40, $0a, $86, $38, $47, $00, $84, $40, $0a, $86, $38, $47, $00, $84, $40, $0a, $86, $38, $47, $00, $84
	.byte $41, $20
	.word @song8ref609
@song8ref708:
	.byte $47, $00, $84, $40, $0a, $86, $3a, $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $3a
	.byte $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $3a, $47, $00, $84, $40, $0a, $00, $47
	.byte $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $3a, $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40
	.byte $0a, $86, $3a, $47, $00, $84, $40, $0a, $86, $3a, $47, $00, $84, $40, $0a, $86, $3a, $47, $00, $84, $40, $0a, $86, $3a
	.byte $41, $20
	.word @song8ref708
	.byte $47, $00, $84
	.byte $41, $20
	.word @song8ref609
	.byte $47, $00, $84
	.byte $41, $20
	.word @song8ref609
@song8ref819:
	.byte $47, $00, $84, $40, $0a, $86, $35, $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $35
	.byte $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $35, $47, $00, $84, $40, $0a, $00, $47
	.byte $00, $40, $0a, $00, $47, $00, $40, $0a, $86, $35, $47, $00, $84, $40, $0a, $00, $47, $00, $40, $0a, $00, $47, $00, $40
	.byte $0a, $86, $35, $47, $00, $84, $40, $0a, $86, $35, $47, $00, $84, $40, $0a, $86, $35, $47, $00, $84, $40, $0a, $86, $35
	.byte $41, $20
	.word @song8ref819
	.byte $47, $00
	.byte $41, $20
	.word @song8ref433
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $47, $00
	.byte $41, $20
	.word @song8ref434
	.byte $42
	.word @song8ch1loop
@song8ch2:
@song8ch2loop:
@song8ref982:
	.byte $8a
@song8ref983:
	.byte $0a, $00, $0a, $00, $0a, $00, $0a, $00, $0a, $00, $0a, $00, $0a, $00, $0a, $00, $0a, $00, $0a, $00, $0a, $00, $0a, $00
	.byte $0a, $00, $0a, $00, $0a, $00, $0a, $00
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $25, $bd, $af, $1d, $83, $25, $83, $22, $81, $24, $bd, $bf, $23, $bd, $21, $ad, $1d, $81, $1e, $81, $00, $85, $1d, $bd
	.byte $bf, $25, $bd, $af, $1d, $83, $25, $83, $22, $81, $24, $bd, $bf, $23, $bd, $21, $ad, $1d, $81, $1e, $81, $00, $85, $1d
	.byte $bd, $bf
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $77, $90
@song8ref1112:
	.byte $30, $85, $7f, $8a, $0a, $00, $77, $90, $2d, $85, $7f, $8a, $0a, $00, $77, $90, $30, $85, $7f, $8a, $0a, $00, $77, $90
	.byte $2d, $85, $7f, $8a, $0a, $00, $77, $90, $2d, $85, $2a, $85, $30, $85, $7f, $8a, $0a, $00, $77, $90, $2d, $85, $7f, $8a
	.byte $0a, $00, $77, $90, $30, $85, $7f, $8a, $0a, $00, $77, $90, $2d, $85, $7f, $8a, $0a, $00, $77, $90, $2d, $85, $2a, $85
	.byte $41, $28
	.word @song8ref1112
	.byte $41, $20
	.word @song8ref982
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $41, $20
	.word @song8ref983
	.byte $42
	.word @song8ch2loop
@song8ch3:
@song8ch3loop:
	.byte $78, $8c
@song8ref1205:
	.byte $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00
	.byte $32, $00, $32, $00, $32, $00, $32, $00
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
@song8ref1330:
	.byte $7c, $8e, $32, $8d, $78, $8c, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00
	.byte $32, $00, $32, $00, $32, $00, $7c, $8e, $32, $8d, $78, $8c, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00
	.byte $32, $00, $32, $00, $32, $00, $32, $00, $32, $00, $32, $00
	.byte $41, $34
	.word @song8ref1330
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $41, $20
	.word @song8ref1205
	.byte $42
	.word @song8ch3loop
@song8ch4:
@song8ch4loop:
@song8ref1409:
	.byte $01, $85, $00, $85, $02, $85, $00, $81, $01, $85, $02, $81, $01, $85, $02, $85, $01, $85, $01, $85, $00, $85, $02, $85
	.byte $00, $81, $01, $85, $02, $81, $01, $85, $02, $85, $01, $85
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $01, $85, $00, $85, $02, $85, $00, $81, $01, $85, $02, $81, $01, $85, $02, $85, $01, $85, $01, $85, $00, $85, $02, $85
	.byte $00, $89, $02, $85, $00, $81, $02, $85, $02, $85
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $24
	.word @song8ref1409
	.byte $41, $1f
	.word @song8ref1409
	.byte $81, $01, $81, $02, $81, $02, $81, $01, $81, $01, $81
	.byte $41, $24
	.word @song8ref1409
	.byte $01, $85, $00, $81, $02, $02, $02, $85, $01, $81, $01, $85, $02, $81, $01, $85, $02, $81, $01, $81, $01, $81, $01, $01
	.byte $01, $85, $00, $85, $02, $85, $00, $81, $01, $85, $02, $81, $01, $81, $01, $81, $02, $81, $02, $81, $01, $81, $01, $81
	.byte $00, $bd, $bf, $bf, $bf, $42
	.word @song8ch4loop
@song9ch0:
	.byte $46, $03
@song9ch0loop:
	.byte $78, $94, $20, $81, $25
@song9ref9:
	.byte $81, $1e, $81, $23, $81, $1d, $81, $22, $81, $1c, $81, $21, $81, $1b, $81, $20, $81, $19, $81, $1e, $81, $18, $81, $1d
	.byte $81, $16, $81, $1a, $81, $00, $8d, $7e, $96
@song9ref42:
	.byte $2e, $85, $45, $85, $27, $8d, $45, $85, $29, $81, $2a, $81, $2c, $81, $00, $81, $2c, $81, $00, $81, $2a, $85, $45, $85
	.byte $29, $8b, $45, $25, $8b, $45, $27, $8b, $45, $22, $95, $45, $95
@song9ref79:
	.byte $1d, $85, $45, $85, $1e, $85, $45, $85, $20, $85, $45, $85, $1e, $85, $45, $85, $8f
	.byte $41, $21
	.word @song9ref42
	.byte $2e, $95, $45, $95
@song9ref103:
	.byte $27, $83, $45, $22, $83, $45, $27, $83, $45, $2a, $83, $45, $29, $83, $45, $26, $83, $45, $29, $83, $45, $2c, $83, $45
	.byte $00, $8d
	.byte $41, $1f
	.word @song9ref42
	.byte $81, $00, $81, $29, $81, $00, $81, $2a, $8d, $29, $8d, $45, $8d
	.byte $41, $11
	.word @song9ref79
	.byte $41, $21
	.word @song9ref42
	.byte $31, $8b, $45, $2e, $8d, $45, $8d
	.byte $41, $18
	.word @song9ref103
	.byte $9c, $23, $95, $45, $85, $20, $95, $45, $85, $22, $9d, $45, $9d, $1e, $95, $45, $85, $1d, $95, $45, $85, $1e, $9d, $45
	.byte $9d, $1a, $95, $45, $85, $1d, $95, $45, $85, $1b, $95, $45, $85, $16, $95, $45, $85, $17, $95, $45, $85, $1a, $95, $45
	.byte $85, $1b, $8b, $45, $1a, $8b, $45, $1b, $8b, $45, $1d, $8b, $45, $1e, $9d, $45, $9d, $20, $9d, $45, $9d, $2a, $8d, $45
	.byte $ad
@song9ref234:
	.byte $00, $85, $2a, $85, $29, $85, $2a, $85, $31, $85, $45, $85, $29, $85, $2a, $85, $45, $ad, $00, $85, $2a, $85, $29, $85
	.byte $27, $85, $25, $8d, $45, $bd
	.byte $41, $16
	.word @song9ref234
	.byte $31, $85, $2e, $85, $29, $85, $45, $8d, $25, $83, $45, $7f, $27, $8d, $45, $ad, $26, $8d, $45, $ad
@song9ref287:
	.byte $77, $49, .lobyte(@env0), .hibyte(@env0), $4a, $94
@song9ref293:
	.byte $1b, $85, $45, $85, $7e, $96, $2b, $85, $45, $85, $24, $8d, $45, $85, $26, $81, $27, $81, $29, $81, $00, $81, $27, $81
	.byte $29, $81, $27, $85, $45, $85, $26, $8b, $45, $22, $8b, $45, $24, $81, $22, $81, $24, $81, $45, $81, $1f, $95, $45, $95
@song9ref341:
	.byte $77, $94, $1a, $85, $45, $8d, $16, $83, $45, $20, $85, $45, $85, $1f, $85, $45, $85, $49, .lobyte(@env0), .hibyte(@env0)
	.byte $4a
	.byte $41, $23
	.word @song9ref293
@song9ref365:
	.byte $83, $45, $26, $83, $45, $27, $85, $45, $85, $26, $8d, $45, $85, $22, $83, $45, $49, .lobyte(@env59), .hibyte(@env59)
	.byte $24, $9d, $45, $9d
	.byte $41, $2b
	.word @song9ref287
	.byte $81, $45, $81, $24, $81, $45, $81, $2b, $8d, $45, $8d
	.byte $41, $0f
	.word @song9ref341
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $23
	.word @song9ref293
	.byte $41, $11
	.word @song9ref365
	.byte $99, $43, $50, $eb, $30, $3c, $81, $49, .lobyte(@env14), .hibyte(@env14), $83, $43, $30, $99, $45, $8d, $00, $bd, $cf
	.byte $cf, $cf, $7f, $a8, $2b
@song9ref439:
	.byte $81, $2b, $81, $2b, $81, $2b, $81, $2b, $81, $2b, $81, $2b, $81, $2b, $81, $00, $9d, $29, $81, $29, $81, $29, $81, $29
	.byte $41, $0f
	.word @song9ref439
	.byte $2b, $81, $00, $9d, $29, $81, $29, $81, $29, $81, $29
@song9ref477:
	.byte $81, $28, $81, $28, $81, $28, $81, $28, $81, $28, $81, $28, $81, $28, $81, $28, $81, $00, $9d, $26, $81, $26, $81, $26
	.byte $81, $26
	.byte $41, $12
	.word @song9ref477
	.byte $8d, $30, $81, $30, $81, $30, $81, $30, $81, $30, $81, $30, $81, $30, $81, $30, $81, $42
	.word @song9ch0loop
@song9ch1:
@song9ch1loop:
	.byte $70, $bf, $75, $94
@song9ref531:
	.byte $25, $8d, $7c, $96, $27, $85, $45, $85, $2a, $8d, $45, $85, $25, $81, $27, $81, $29, $81, $00, $81, $29, $81, $00, $81
	.byte $27, $85, $45, $85, $25, $8b, $45, $20, $8b, $45, $23, $8b, $45, $1e
@song9ref569:
	.byte $95, $45, $95, $75, $00, $85, $94, $25, $81, $27, $81, $2a, $85, $20, $81, $22, $81, $29, $85, $1e, $81, $20, $81, $27
	.byte $85, $1d, $81, $1e, $81
	.byte $41, $23
	.word @song9ref531
	.byte $2a, $95, $45, $85, $29, $85, $45, $85, $75, $94
	.byte $41, $18
	.word @song9ref103
	.byte $41, $21
	.word @song9ref531
	.byte $81, $00, $81, $23, $81, $00, $81, $22
	.byte $41, $1b
	.word @song9ref569
	.byte $41, $23
	.word @song9ref531
	.byte $2a, $95, $45, $85, $29, $85, $45, $85, $75, $94
	.byte $41, $18
	.word @song9ref103
@song9ref644:
	.byte $1b, $81, $1d, $81, $1e, $81, $20, $81, $22, $81, $20, $81, $1e, $81, $1d, $81, $1b, $81, $1d, $81, $1e, $81, $20, $81
	.byte $25, $81, $20, $81, $1e, $81, $1d, $81, $1b, $81, $1d
	.byte $41, $1d
	.word @song9ref9
	.byte $41, $23
	.word @song9ref644
	.byte $41, $1d
	.word @song9ref9
	.byte $41, $23
	.word @song9ref644
	.byte $41, $1d
	.word @song9ref9
	.byte $41, $23
	.word @song9ref644
	.byte $41, $1d
	.word @song9ref9
	.byte $41, $23
	.word @song9ref644
	.byte $41, $1d
	.word @song9ref9
	.byte $49, .lobyte(@env39), .hibyte(@env39), $9c
@song9ref710:
	.byte $22, $9d, $45, $9d, $9c, $25, $9d, $45, $8d, $1d, $85, $45, $85, $1e, $85, $45, $85, $19, $8d, $45, $8d, $1d, $9d, $45
	.byte $8d, $49, .lobyte(@env39), .hibyte(@env39)
	.byte $41, $18
	.word @song9ref710
	.byte $16, $85, $45, $85, $78, $49, .lobyte(@env0), .hibyte(@env0), $4a, $94, $1b, $8d, $16, $8d, $1b, $8d, $1e, $8d, $1d
	.byte $8d, $1a, $8d, $22, $8d, $16, $8d, $7a, $9c
@song9ref769:
	.byte $18, $85, $14, $85, $1b, $85, $14, $85, $1f, $85, $14, $85, $18, $85, $14, $85, $16, $85, $13, $85, $1d, $85, $13, $85
	.byte $1f, $85, $13, $85, $1a, $85, $13, $85
	.byte $41, $20
	.word @song9ref769
	.byte $41, $20
	.word @song9ref769
	.byte $41, $20
	.word @song9ref769
	.byte $41, $20
	.word @song9ref769
	.byte $41, $20
	.word @song9ref769
	.byte $41, $20
	.word @song9ref769
	.byte $41, $12
	.word @song9ref769
	.byte $1a, $85, $1b, $85, $1d, $85, $1f, $85, $1d, $85, $22, $85, $1f, $85, $76, $b6
@song9ref838:
	.byte $16, $81, $1a, $81, $1b, $81, $16, $81, $1a, $81, $1b, $81, $16, $81, $1a, $81, $1b, $81
	.byte $41, $12
	.word @song9ref838
	.byte $41, $12
	.word @song9ref838
	.byte $41, $12
	.word @song9ref838
@song9ref865:
	.byte $16, $81, $1a, $81, $1b, $81, $16
@song9ref872:
	.byte $81, $18, $81, $1c, $81, $1d, $81, $18, $81, $1c, $81, $1d, $81, $18, $81, $1c, $81, $1d
	.byte $41, $12
	.word @song9ref872
	.byte $41, $12
	.word @song9ref872
	.byte $41, $12
	.word @song9ref872
	.byte $81, $18, $81, $1c, $81, $1d, $81, $18, $81
	.byte $41, $12
	.word @song9ref838
	.byte $41, $12
	.word @song9ref838
	.byte $41, $12
	.word @song9ref838
	.byte $41, $12
	.word @song9ref838
	.byte $41, $19
	.word @song9ref865
	.byte $41, $12
	.word @song9ref872
	.byte $41, $12
	.word @song9ref872
	.byte $41, $12
	.word @song9ref872
	.byte $81, $18, $81, $1c, $81, $1d, $81, $18, $81, $42
	.word @song9ch1loop
@song9ch2:
@song9ch2loop:
	.byte $8a, $33, $81, $2c, $81, $31, $81, $2a, $81, $2f, $81, $28, $81, $2d, $81, $26, $81, $2b, $81, $24, $81, $29, $81, $22
	.byte $81, $27, $81, $20, $81, $26, $81, $1f, $81
@song9ref978:
	.byte $1b, $bd, $19, $bd, $17, $bd, $16, $bd, $14, $bd, $16, $bd, $17, $9d, $1e, $8d, $1d, $8d, $1b, $95, $1d, $81, $1b, $81
	.byte $1a, $9d
	.byte $41, $1a
	.word @song9ref978
	.byte $0f, $bd, $0f, $bd, $0f, $bd, $0f, $bd, $0f, $bd, $0f, $bd, $0f, $bd, $0f, $bd, $0b, $bd, $0d, $bd
@song9ref1027:
	.byte $0f, $85, $00, $8d, $0f, $85, $19, $81, $00, $81, $1b, $81, $00, $81, $0f, $85, $00, $8d, $0f, $85, $00, $85, $0d, $85
	.byte $0f, $85, $00, $85
	.byte $41, $1c
	.word @song9ref1027
	.byte $41, $1c
	.word @song9ref1027
	.byte $41, $1c
	.word @song9ref1027
	.byte $0f, $85, $00, $85, $0b, $87, $00, $0b, $87, $00, $0b, $87, $00, $0b, $87, $00, $0b, $83, $00, $0b, $00, $0b, $00, $0a
	.byte $87, $00, $0a, $87, $00, $0a, $87, $00, $0a, $87, $00, $0e, $81, $11, $81, $16, $81, $0a, $81
@song9ref1107:
	.byte $18, $83, $00, $18, $00, $18, $00, $18, $83, $00, $18, $00, $18, $00, $18, $00, $18, $00, $18, $83, $00, $18, $83, $00
	.byte $18, $00, $18, $00, $16, $83, $00, $16, $00, $16, $00, $16, $83, $00, $16, $00, $16, $00, $16, $00, $16, $00, $16, $83
	.byte $00, $16, $83, $00, $16, $00, $16
@song9ref1162:
	.byte $00, $14, $83, $00, $14, $00, $14, $00, $14, $83, $00, $14, $00, $14, $00, $14, $00, $14, $00, $14, $83, $00, $14, $83
	.byte $00, $14, $00, $14
@song9ref1190:
	.byte $00, $13, $83, $00, $13, $00, $13, $00, $13, $83, $00, $13, $00, $13, $00, $13, $00, $13, $00, $13, $83, $00, $13, $83
	.byte $00, $13, $00, $13
	.byte $41, $1d
	.word @song9ref1162
@song9ref1221:
	.byte $0e, $83, $00, $0e, $00, $0e, $00, $0e, $83, $00, $0e, $00, $0e, $00, $0e, $00, $0e, $00, $0e, $83, $00, $0e, $83, $00
	.byte $0e, $00, $0e, $00, $11, $83, $00, $11, $00, $11, $00, $11, $83, $00, $11, $00, $11, $00, $11, $00, $11, $00, $11, $83
	.byte $00, $11, $83, $00, $11, $00, $11
	.byte $41, $1c
	.word @song9ref1190
	.byte $00
	.byte $41, $6f
	.word @song9ref1107
	.byte $41, $1d
	.word @song9ref1162
	.byte $41, $37
	.word @song9ref1221
	.byte $41, $1c
	.word @song9ref1190
@song9ref1292:
	.byte $00, $0c, $8b, $00, $0c, $8b, $00, $0c, $8b, $00, $0c, $8b, $00, $0a, $8b
	.byte $41, $0f
	.word @song9ref1292
	.byte $41, $0f
	.word @song9ref1292
	.byte $41, $0f
	.word @song9ref1292
@song9ref1316:
	.byte $00, $08, $8b, $00, $08, $8b, $00, $08, $8b, $00, $08, $8b, $00, $07, $8b
	.byte $41, $0f
	.word @song9ref1316
@song9ref1334:
	.byte $00, $0a, $8b, $00, $0a, $8b, $00, $0a, $8b, $00, $0a, $8b, $00, $07, $8b
	.byte $41, $0f
	.word @song9ref1334
	.byte $00, $42
	.word @song9ch2loop
@song9ch3:
@song9ch3loop:
	.byte $bf
@song9ref1358:
	.byte $7f, $8e, $32, $8d, $7a, $8c
@song9ref1364:
	.byte $31, $85, $72, $31, $81, $31, $81, $7a, $31, $85, $75, $31, $81, $77, $31, $81, $7a, $31, $85, $72, $31, $85, $7a, $31
	.byte $85, $72, $31, $81, $31, $81, $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $10
	.word @song9ref1364
	.byte $7f, $8e, $32, $8d, $77, $8c
@song9ref1460:
	.byte $2f, $85, $2f, $85, $32, $85, $2f, $85, $2f, $85, $2f, $85, $32, $85, $2f, $85
	.byte $41, $10
	.word @song9ref1460
	.byte $41, $10
	.word @song9ref1460
	.byte $41, $10
	.word @song9ref1460
	.byte $41, $10
	.word @song9ref1460
	.byte $41, $10
	.word @song9ref1460
	.byte $41, $10
	.word @song9ref1460
	.byte $41, $10
	.word @song9ref1460
	.byte $41, $10
	.word @song9ref1460
	.byte $2f, $85, $2f, $85, $32, $85, $2f, $85, $2f, $85, $2f
@song9ref1511:
	.byte $85, $7f, $8e, $32, $8d, $77, $8c, $2f, $85, $00, $85, $32, $85, $32, $85, $2f, $85, $00, $85, $32, $85, $32, $85, $2f
	.byte $85, $00, $85, $32, $85, $32
	.byte $41, $1a
	.word @song9ref1511
	.byte $41, $1a
	.word @song9ref1511
	.byte $41, $1a
	.word @song9ref1511
	.byte $85, $2f, $85, $00, $85, $7a, $c2, $33, $9d, $33, $9d, $33, $8d, $33, $8d, $33, $8d, $33, $8d
	.byte $41, $18
	.word @song9ref1358
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $10
	.word @song9ref1364
	.byte $41, $18
	.word @song9ref1358
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $10
	.word @song9ref1364
	.byte $41, $18
	.word @song9ref1358
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $10
	.word @song9ref1364
	.byte $41, $18
	.word @song9ref1358
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $16
	.word @song9ref1364
	.byte $7a
	.byte $41, $10
	.word @song9ref1364
@song9ref1629:
	.byte $7c, $8e, $32, $8d, $77, $8c
@song9ref1635:
	.byte $2f, $81, $2f, $81, $2f, $81, $2f, $81, $00, $85, $32, $85, $2f, $85, $2f, $85, $00, $85, $32, $85, $32, $85, $00, $85
	.byte $41, $18
	.word @song9ref1635
	.byte $41, $18
	.word @song9ref1635
	.byte $41, $14
	.word @song9ref1635
	.byte $41, $16
	.word @song9ref1629
	.byte $41, $16
	.word @song9ref1629
	.byte $41, $16
	.word @song9ref1629
	.byte $41, $16
	.word @song9ref1629
	.byte $42
	.word @song9ch3loop
@song9ch4:
@song9ch4loop:
@song9ref1684:
	.byte $01, $85, $00, $85, $01, $85, $00, $85, $01, $85, $00, $85, $01, $85, $02, $02, $02, $02
@song9ref1702:
	.byte $01, $85, $01, $81, $01, $81, $02, $85, $01, $81, $01, $85, $01, $81, $01, $85, $02, $85, $01, $85, $01, $85, $01, $85
	.byte $02, $85, $01, $85, $01, $81, $02, $81, $01, $85, $02, $85, $01, $81, $01, $81
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $19
	.word @song9ref1702
@song9ref1751:
	.byte $81, $02, $81, $02, $81, $02, $81, $01, $85, $01, $81, $01, $81, $02, $81, $01, $81, $01, $81, $01, $81
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $19
	.word @song9ref1702
	.byte $41, $15
	.word @song9ref1751
@song9ref1787:
	.byte $01, $85
@song9ref1789:
	.byte $01, $85, $02, $85, $01, $81, $01, $85, $01, $81, $01, $85, $02, $85, $01, $81, $01, $81, $83, $01, $81
	.byte $41, $0f
	.word @song9ref1789
	.byte $85
	.byte $41, $17
	.word @song9ref1787
	.byte $41, $0f
	.word @song9ref1789
	.byte $85
	.byte $41, $17
	.word @song9ref1787
	.byte $41, $0f
	.word @song9ref1789
	.byte $85
	.byte $41, $17
	.word @song9ref1787
	.byte $41, $0f
	.word @song9ref1789
	.byte $85
	.byte $41, $17
	.word @song9ref1787
	.byte $41, $0e
	.word @song9ref1789
	.byte $02, $81, $02, $81
@song9ref1845:
	.byte $01, $85, $00, $95, $02, $85, $00, $8d, $01, $85, $00, $85, $01, $85, $00, $85, $01, $85, $02, $85, $01, $85
	.byte $41, $16
	.word @song9ref1845
	.byte $41, $16
	.word @song9ref1845
	.byte $01, $85, $01, $85, $00, $85, $01, $85, $02, $85, $02, $85, $01, $85, $00, $8d, $01, $85, $00, $85, $01, $85, $02, $85
	.byte $01, $85, $02, $85, $01, $85, $01, $85, $00, $95, $01, $85, $00, $95
	.byte $41, $0f
	.word @song9ref1684
	.byte $81, $02, $81
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $19
	.word @song9ref1702
	.byte $41, $15
	.word @song9ref1751
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $28
	.word @song9ref1702
	.byte $41, $19
	.word @song9ref1702
	.byte $41, $15
	.word @song9ref1751
@song9ref1947:
	.byte $01, $81, $00, $85, $01, $81, $02, $81, $00, $81, $01, $81, $00, $81, $01, $81, $00, $81
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $41, $12
	.word @song9ref1947
	.byte $01, $81, $00, $85, $01, $81, $02, $81, $01, $81, $01, $81, $02, $81, $01, $81, $02, $81, $42
	.word @song9ch4loop
