song_intro = 0
song_ocean = 1
song_sword = 2
song_sword_2 = 3
song_northernlight = 4
song_northernlight_2 = 5
song_glaceir = 6
song_bit_roots = 7
song_eram = 8
song_burning_eyes = 9
song_twisted = 10
song_max = 11

.if SONG_STRINGS
song_strings:
.asciiz "INTRO"
.asciiz "OCEAN"
.asciiz "SWORD"
.asciiz "SWORD 2"
.asciiz "NORTHERNLIGHT"
.asciiz "NORTHERNLIGHT 2"
.asciiz "GLACEIR"
.asciiz "BIT ROOTS"
.asciiz "ERAM"
.asciiz "BURNING EYES"
.asciiz "TWISTED"
.endif
