sfx_sfx_door = 0
sfx_sfx_equip = 1
sfx_sfx_sword = 2
sfx_sfx_spear = 3
sfx_sfx_hit = 4
sfx_sfx_kill = 5
sfx_sfx_dink = 6
sfx_sfx_lvup = 7
sfx_sfx_damage = 8
sfx_sfx_heal = 9
sfx_sfx_text = 10
sfx_sfx_textend = 11
sfx_sfx_icekey = 12
sfx_sfx_jump = 13
sfx_sfx_raft = 14
sfx_sfx_dooropen = 15
sfx_sfx_moveblock = 16
sfx_sfx_usedup = 17
sfx_max = 18

.if SFX_STRINGS
sfx_strings:
.asciiz "SFX_DOOR"
.asciiz "SFX_EQUIP"
.asciiz "SFX_SWORD"
.asciiz "SFX_SPEAR"
.asciiz "SFX_HIT"
.asciiz "SFX_KILL"
.asciiz "SFX_DINK"
.asciiz "SFX_LVUP"
.asciiz "SFX_DAMAGE"
.asciiz "SFX_HEAL"
.asciiz "SFX_TEXT"
.asciiz "SFX_TEXTEND"
.asciiz "SFX_ICEKEY"
.asciiz "SFX_JUMP"
.asciiz "SFX_RAFT"
.asciiz "SFX_DOOROPEN"
.asciiz "SFX_MOVEBLOCK"
.asciiz "SFX_USEDUP"
.endif
