#ifndef __ISLAND__ROOMS_H_
#define __ISLAND__ROOMS_H_

extern const unsigned char* const island_rooms[];
extern const unsigned char island_room_0[];
extern const unsigned char island_room_1[];
extern const unsigned char island_room_2[];
extern const unsigned char island_room_3[];
extern const unsigned char island_room_4[];
extern const unsigned char island_room_5[];
extern const unsigned char island_room_6[];
extern const unsigned char island_room_7[];
extern const unsigned char island_room_8[];
extern const unsigned char island_room_9[];
extern const unsigned char island_room_10[];
extern const unsigned char island_room_11[];
extern const unsigned char island_room_12[];
extern const unsigned char island_room_13[];
extern const unsigned char island_room_14[];
extern const unsigned char island_room_15[];
extern const unsigned char island_room_16[];
extern const unsigned char island_room_17[];
extern const unsigned char island_room_18[];
extern const unsigned char island_room_19[];
extern const unsigned char island_room_20[];
extern const unsigned char island_room_21[];
extern const unsigned char island_room_22[];
extern const unsigned char island_room_23[];
extern const unsigned char island_room_24[];
extern const unsigned char island_room_25[];
extern const unsigned char island_room_26[];
extern const unsigned char island_room_27[];
extern const unsigned char island_room_28[];
extern const unsigned char island_room_29[];
extern const unsigned char island_room_30[];
extern const unsigned char island_room_31[];
extern const unsigned char island_room_32[];
extern const unsigned char island_room_33[];
extern const unsigned char island_room_34[];
extern const unsigned char island_room_35[];
extern const unsigned char island_room_36[];
extern const unsigned char island_room_37[];
extern const unsigned char island_room_38[];
extern const unsigned char island_room_39[];
extern const unsigned char island_room_40[];
extern const unsigned char island_room_41[];
extern const unsigned char island_room_42[];
extern const unsigned char island_room_43[];
extern const unsigned char island_room_44[];
extern const unsigned char island_room_45[];
#endif