#+title:MANTLE.NES Video Script

* Section 0: About the Video & Acknowledgements

Hi! I'm drmelon, and recently I worked on a half-demake, half-fangame for the original NES, based on a certain set of minigames from Deltarune Chapter 3. If you'd like to play it, you can check it out on my itch page, which I've linked in the description. Of course, it contains spoilers for Deltarune Chapter 3, as does this video - so go and play Deltarune first, so you don't get spoiled!

...

Now that the spoiler alert is done, welcome!
I wanted to make a video to share some of the inner workings of MANTLE.NES with everyone. I love watching videos from channels like Retro Mechanics Explained, or Wye's series on rebuilding Super Mario World from scratch in the Godot engine; I always find the way they share the technical details of retro games to be fascinating and informative, and so I wanted to do something similar for everyone who was curious about this fangame.

First though, there's a few people I want to thank.

I'd first like to thank leafcodes, for her awesome music. Her NES arrangements of the Sword Route tracks from Deltarune are fantastic and super faithful to the originals, and her own unique track, TWISTED, is absolutely awesome. Huge thanks to her for making this game sound as good as it does! I've linked her bandcamp in the description, go check it out!
I want to thank Bro3256 for the awesome playthrough video on hardware - it's really, really cool to see the game running on an actual NES, and the video also helped a lot of people find my fangame. Thank you for putting it out there!
Next, I want to thank everyone involved with the NES homebrew development scene; absolutely none of what I managed to make would even be slightly possible without the hard work of so many people.
Finally, I want to list out the tools I used to make this game on the screen - I'll link them all in the description so you can check them out too if you're interested. These made my life so much easier, and I'll talk more in depth about how I used them as the video goes on.

Alright, with my thanks and gratitude given out, let's get into why and how I got started with the project!

* Section 1: Why?

When I played Deltarune Chapter 3 back in June, I was immediately struck by how much love and care was poured into the Tenna board games. They really do feel and play like early Zelda titles, and the way the games are presented feels very internally consistent - it really sells the idea that this is some in-world console being represented. It reminded me of other fantasy consoles, like Lexaloffle's PICO-8 or the LX system from Mossmouth's UFO 50; the way that they have their own limitations and restraints that allow them to replicate the exact feeling of playing games from the mid-to-late eighties. And when I got to the S-Rank room, and found the backstage console and started playing... I mean, wow! The way the game unfolds builds up such a specific atmosphere, it was kind of electrifying. I remember being a kid, playing on the Megadrive and on the family MS-DOS PC, finding weird buggy secrets - there's a kind of gripping, transgressive fear, where you kind of feel your brain yelling "WE SHOULDN'T BE HERE!" but you somehow can't stop yourself from exploring... until you make the console glitch out in a weird way, and you hammer the reset button like your life depends on it! In case, you know, it comes alive and tries to eat you or something. I was a normal kid and grew up to be completely normal.

Playing the minigames reminded me of those feelings; the way it's like a strange, bleak reflection of the fun stuff you just played, and the way it mirrors the evil routes in Undertale contribute to that broken-and-creepy feeling, and it left me wondering how many kids were feeling that same excited terror I once felt.

So with the really impressive fantasy console stuff, and the big impression it left on me, I very quickly started thinking about how I could demake the game for a real console. I was so excited that I actually started this project less than a week after Deltarune Chapter 3 came out, and then, uh... spent the next three months of my spare time on it.

I was already familiar with programming on the NES, at least a little bit. But, I hadn't tried anything close to this scale before, so I knew it'd be a slightly longer journey - and because of that familiarity, I knew right off the bat that I'd have to make some changes or find ways to adapt things differently. I did initially intend to make a 1-to-1 demake, but as things began to change more and more due to various constraints and things, I thought it would be a lot more fun (and a little bit metatextually more accurate) to make larger changes, and build it into its own little cohesive narrative.

So, with my rationale described and that little bit of background, let's get into the actual technical nuts and bolts...

* Section 2: The Cartridge, Setup, and Tools

I could have written the entire thing in 6502 Assembly. Assembly is a low-level programming language where you write the machine code instructions you want the processor to perform; you're directly commanding the console's processor. It might seem complex at first, but it's actually simpler in a lot of ways than writing more abstract code, since there's only so much you can do. However, it would have taken me a much longer time to get everything I wanted written, and I wanted to build this game during my limited free time in the evenings and weekends, so instead I decided to use the C programming language.

C is a compiled language; I write more abstract code in a way that lets me ignore the exact instructions that the CPU needs to execute, and instead focus on the logic and arithmetic I want to compute instead. Then, the compiler (in this case, CC65) turns my source code into the same assembly instructions I would have written manually. It can't always do this in the most 100% efficient way, but C compilers these days generate very, very optimized code most of the time, so it's definitely worth trading runtime and storage efficiency for saving myself a bunch of real-world time.
Using C also let me use a very useful library called "neslib". This library, initially created by a developed named "shiru" and maintained by the NES development community to this day, has a collection of handy shorthand functions and macros for very common operations on the NES, like controlling parts of the graphics hardware, setting up registers, and things like that.

To kick things off, I used a tool called "create-nes-game" to start a new project; this is a fantastic tool that will automatically install the compiler, assembler, optional C libraries like neslib, a NES emulator, and let me set up some configuration for the NES cartridge. For the emulator, I chose to use Mesen. It's a very accurate emulator, and contains a wealth of very useful debugging tools - even a profiler, for measuring the performance of different sections of code. Additionally, the debugging symbols that the CC65 compiler produces alongside the assembled ROM can be loaded by Mesen, to let me search for my variables by name in the memory viewer, and view my code's function names in the debugger. This made it way easier to find out what was going wrong when bugs showed up.

One of the interesting things about cartridge-based games is the fact that the game cartridges themselves are pieces of independent hardware. The pins in the cartridge slot allow the CPU of the NES to communicate with the chips inside the cartridge directly - making an actual, physical connection to the read-only memory (or ROM) chips, which the console interprets as a section of memory usually beginning at the address 0x8000 and ending at 0xFFFF, the biggest number the console can represent in its 16-bit address space. The earliest NES games like the original Super Mario Bros came on a cartridge format known in the NES development community as "NROM"; the cartridge consisted of up to 32 kilobytes of PRG (program) ROM, which contained all of the game's code and audio, and 8 kilobytes of CHR (character) ROM, which contained the entire game's graphics data. This really isn't a lot of space to work with, so what happens if your game is just a little bit too big to fit in an NROM?

This problem can be overcome thanks to the aforementioned way that cartridge-based games are built using hardware - if you need more ROM space, why not just add more ROM chips to the cartridge? Well, the console doesn't know you've done this, and so the instructions that it uses to communicate with the cartridge have no way to access these new chips, since it can still only see a window from 0x8000 to 0xFFFF. So, you add an extra chip called a "mapper chip". It reserves a few memory addresses for its own registers; when these addresses are filled with values, it can read the values and switch which of the ROM chips are connected to the console's pins. This technique is called "bank switching". The console doesn't actually "know" the connections are being changed like this; it all just looks like regular ROM space, but it works - as long as you don't need something from two different places at exactly the same time, that is! And because they are hardware, mapper chips can do a lot more than just increase the amount of ROM you have available, and can actually add new features that weren't there before.

When Nintendo wanted to bring the first entry in the Legend of Zelda series to the international market, they had a problem. You see, Zelda 1 was originally released for the Famicom Disk System which was an add-on peripheral for the NES' original Japanese incarnation, the Famicom (short for Family Computer). The NES was designed as a gaming-only entertainment system rather than a home computer, to thread the needle between the recent market crash of home computers in the US, and the massive popularity of relatively affordable home computers in the European market.

As the name suggests, the Disk System used removable disks, similar in nature to floppy disks. These had a larger capacity of 64 kilobytes on each side - a total of 128 kilobytes! Zelda 1 was written for this new format, and took full advantage of the space available for its large interconnected world. But, of course, when it was time to bring it to the NES, there wasn't enough room on the standard NROM cartridges for the game! Not only that, but the game allowed players to save their progress in save files on the disk, which wasn't possible on the NES. And playing Zelda 1 without being able to save would be pretty painful.

Nintendo designed a mapper chip called the "MMC1" in order to build the cartridge-based version of Zelda 1. The chip massively increased the storage capacity, up to a maximum of 256 kilobytes of PRG ROM and 128 kilobytes of CHR ROM. It also supported battery-backed SRAM; a writable chip that could store save data as long as a battery inside the cartridge supplied power to it, which meant players could save their game just like the disk system version of Zelda 1! This made the chip a very popular choice, and more than 300 games used the MMC1.
I really wanted to continue the same callbacks that the Deltarune minigames were making to older Zelda titles, so I decided to build my fangame with this chip in mind! It can operate in a few different modes; for this project, I use the PRG ROM banks in 16kb mode. That is, there's a main, fixed bank that's 16kb long - what would usually be the first half of a regular PRG ROM. This doesn't change, so certain pieces of game code can stay in that bank and always be available to the console. The second 16kb is what gets switched in and out, so I can use this for level data, monster behaviour code, dialogue text... all kinds of stuff!

Let's move on to something a little bit more visual...

* Section 3: Tiles, and Colours

The game's resolution was the first thing I had to contend with. The game world is divided up into rooms that take up most of the screen's display; the characters can travel between rooms at the edges, and the screen will scroll over to reveal the next room. Most game consoles from the era that Deltarune's fantasy console mimics drew backgrounds using Tiles, and the Deltarune fantasy console is no different.

Each room in the game appears to consist of a grid of 12 by 8 tiles. Each tile is 16 pixels wide, and 16 pixels tall. However, the game's HUD is displayed in an area 16 pixels tall along the top of the screen, and can be divided into smaller 8-by-8 tiles; so it's probably more accurate to say that the main play area also uses 8x8 tiles, and is 24 tiles wide and 16 tiles tall. Combining this with the HUD area, the total console resolution is 24 tiles by 18 tiles - or 192 by 144, a 4:3 aspect ratio - which is the same aspect ratio as Deltarune itself, and the most common aspect ratio for TVs in the 80s and 90s. It's also the same vertical resolution as the original Game Boy and Game Boy Color handhelds, but they were a little narrower, at only 160 pixels wide - so the rooms wouldn't fit on those handhelds on a single screen.

Lucky for me, the NES also uses 8x8 tiles to render backgrounds, but output resolution is actually quite a bit bigger. It supports a maximum resolution of 256x240 pixels, or 32x30 tiles, at the slightly awkward aspect ratio of 8:7. On top of this, when outputting a 60Hz NTSC video signal rather than a 50Hz PAL signal, the top and bottom 8 pixels are cut off, resulting in a resolution of 256x224 pixels, or 32x28 visible tiles. I decided to go with making the game in NTSC form, for no real reason other than I prefer 60Hz to 50.

So, that left me with a lot of empty space when I put a room on the screen. I didn't want to expand the rooms out to the full screen size, as I would have had to redesign most of the rooms and encounters - and I did initially start with making it a 1-to-1 copy. So, I made the decision to display the world in the middle of the screen, and put a border around the edges.

But... hold on a second. I'm jumping the gun a little bit - I can't talk about entire rooms before I talk about the tiles themselves. I couldn't actually display the desert tiles in their original form on the NES. Why? Well, the graphics chip on the NES, called the PPU, only supports 64 colours - and of those 64, only 16 of them can be used at one time for the backgrounds of the game. And for each group of 4x4 tiles, only one subset four of those 16 can be used. And, to top it all off... the first entry of each of those 4-colour-long palettes is the background colour, and is actually shared amongst all of them - so I really only had *three* colours to work with per tile. And if we count the colours in this palm tree tile, there are... four. And the colours don't exactly match the NES ones either.

I copied the tiles out from screenshots and videos of the Deltarune minigames, working in my favourite sprite editing software, Aseprite. I started with the sand, the bricks of the pyramid, the big door, these rocks, and the palm trees. I loaded up the NES colour palette in Aseprite to see which 4-colour palettes I could use for each of the tiles. I eventually ladnded on a solution where I use a dark brown as the background colour. That at least gave me the colour I needed to draw the palm tree tile's trunk - and I could then draw the sand, the darker sand, and the leaves without trouble.
Then, I used a really great application called Nostalgic Assets Workshop, which let me convert my pixel art from regular image files into the specific tile data format the NES expects them to be in inside CHR ROM. It also let me double-check my palettes, and test laying them out the way the NES would.

Of course, by setting the background color to that dark brown, the borders of the screen became brown. So I reserved one of the palette groups for the borders and HUD; I set black as one of the foreground colours, and actually draw solid black tiles where the border is. Text uses white and black, and the status bars use a deep red for visual contrast.

And just like that, I had enough colours to draw the tile! I used the other two entries for water tiles, and for the rock tiles. By using these same color palettes on a number of different tiles (and by cutting out a few of the more complex shapes, like the curves on the red sand here), I had enough colours and tiles to draw any of the desert rooms!


# *MOVE THIS SECTION ->* And lucky for us, we can use an entirely different set of 16 colours for sprites; the same limitations apply, where each sprite tile can only use 3 colours, with a shared background colour (which is treated as transparent), so our little Kris sprite has an issue. Not enough colours for the scarf. So we'll just draw a different sprite on top for the scarf, which is a well-known technique on the NES. It was used in Megaman for his face, for example! The NES can only draw 8 sprites per horizontal scanline, so we might have to be careful, but the scarf is so thin this only affects two scanlines which isn't a huge deal.

# Let's try scrolling the screen to view the room next to this one...

# Oh. Wait.

#
And that segues neatly into the next section...

* Section 4: Level Data

Remember back when I was talking about mapper chips, and bank switching? Well, each bank of PRG ROM the MMC1 gives us is roughly 16kb in size, or 16384 bytes. Sounds like a lot of space! So, let's look at the 8x8 tiles we have in CHR ROM for the desert area. Each of them can be referred to with a number, and we can build a whole room by "painting" it using these numbers. Each number can only go up to 255, so each number can be stored in the ROM as a single 8-bit byte.
Because each room is 24 by 16 tiles, and we use one byte per tile, that means we would need to store 384 bytes per room. The desert contains about 34 rooms, give or take a couple of duplicates. So, we'd be using about 13kb out of our 16kb just for the desert rooms alone.
This is way too much for just one environment; since we have all the other areas to do as well, there's got to be better way than having half of our entire rom just be level data. And of course, there is.

The first thing to do here is notice that the game actually really only uses 16x16 pixel tiles - that is, 12 by 8 tiles for each room. Instead of individually referencing the 8x8 tiles, I instead stored the level data by numbering only the 16x16 tiles. Then, I have a separate list of which grouping of 4 8x8 tiles to use. When the level data is loaded, the game checks this list to know which actual tiles to tell the NES PPU to use. This is a very common technique, and these groups of tiles are called "metatiles".
This immediately cuts the size per level down from 384 bytes to 96 bytes. But we can go further!
Notice how a lot of each level contains the same data over and over? Like in this room, where there are these large stretches of rock, or this room, which is just... trees?
A super common technique used very widely in NES games (and in file compression and other fields) is called "run length encoding". Instead of listing out every tile, you instead start counting how many tiles are the same as your current tile; then, when the next tile is different, you write in the data what the tile's index was, and how many there were. This means that you use two bytes each tile the tile index changes, but only when it changes. So, for a room with a lot of repetition like the tree room, it goes from being this... to just this. Each level takes a different amount of space in the ROM, and some end up even being a little larger than before, but the overall space saving is enormous!
Loading this data is just as simple; read the tile index and amount, then put that many of that tile on the screen. Keep going until the data stops!

That's not quite the full picture for the level data format, though. There's a few other things I need to track per level, like which other rooms a room connects to, and which monsters and items should spawn in the room and where.
We'll get to that in a second - I want to talk about how I got this data into the ROM, first!

Using the pixel art tilesheets I made before in Aseprite, I went and created a new project in LDTK, a free 2D level editing tool. It's similar to TilEd for anyone who happens to be familiar with that, and basically lets me put down tiles and arrange rooms in a simple what-you-see-is-what-you-get editor. LDTK's file format is super easy to parse and read, as the tool is intended for general use for making 2D games, and it also records information about which rooms are next to each other, which was super useful for my purposes. The data isn't exactly compatible with the NES as-is though, so I wrote a Python script that reads the data for each level in the LDTK project, and spits out C code files that I then compile as part of the game ROM, directly producing the data for the game to use. It performs the run length encoding compression I mentioned earlier, to make sure the level data stays small. And, because LDTK records which rooms neighbour other rooms, I add four bytes at the start of every level. Each byte is the ID of another room that this room connects to, in the order Down, Right, Up, Left. The ID of each room is just the number that LDTK gives it when it is created, so I can add, move, and delete rooms at any time in LDTK and these connections are automatically updated when I run my script!

This made it really fast for me to build out the levels as they were in the original version in Deltarune; it was also convenient enough that I was able to hand over the Island environment to leafcodes, who as I mentioned before did all the music for the project. She was able to build out the entire island environment in a single day!

LDTK also supports placing entities; monsters, items like the sword, rafts, and even "teleporters" for things like staircases were placed this way. Then, after the run-length-encoded tile data, I add a set of 6 bytes for every single entity in the map.
The first byte says what kind of thing this is - a monster, a teleporter, an item, et cetera.
The second and third bytes are the X and Y coordinates of where the object should be spawned in the level.
The fourth byte is used to control what subtype of object it is - for example, the exact kind of monster. For teleporters, this is the destination room index.
The fifth byte is for any extra information for monsters. For example, Walker-type monsters in the ice palace are sometimes invincible, so this flag controls that. For teleporters, this is the destination X coordinate.
The sixth and final byte is used by monsters to record their unique ID within each environment. This is so that when they get killed by the player, they won't be spawned again when the room is re-loaded, as we can check and see if that monster's ID is in the list of monsters killed by the player. For teleporters, it's the destination Y coordinate.

Then, I write a single byte with the value 128 at the end. This tells the loading code that there's no more entity data for this level, and it stops loading the level! Otherwise, it would just start reading the next level's room bytes as monster spawn information, and get really confused...

So now I have rooms, and rooms connected to other rooms! Let's scroll the screen to move from room to room...

Oh. Well...

The NES has no concept of layers for its backgrounds; the HUD and the room are all on the same part of the screen, so they'll scroll together. And while it is possible to split the screen into a scrolling part and a non-scrolling part, like in many NES games, we can only easily do that for vertical sections, and not these horizontal sections.
So... I had to take out the scrolling part. I did this by blanking out the screen by turning off the background, moving the player's sprite as *if* they were being scrolled, and then turning it back on after loading the next room. It's not perfect, but it gets the idea across just enough to work.

We have a world now, and we can move around it! But wait. How did this get here..?

* Section 5: Sprites

Sprites are how the NES renders moving objects. They are made of 8x8 tiles, just like the backgrounds, but they can individually be placed anywhere on the screen. Sprites can use a different 16 color palette from the background, and each sprite can have 4 colors, with one color reserved as a shared transparent color - which means effectively 3 colors per 8x8 sprite. Just like tiles and metatiles, it's very common to use multiple sprites together to draw a single object as a metasprite!
But wait... what's this? This suspiciously Kris-shaped sprite actually has four colors in it!
Well... anyone who is familiar with NES game development already knows this trick and is yelling something like "that's just the Megaman face trick!" at the screen. And they're right! What I've done here is actually draw another sprite on top of the 4 sprites that make up the player's overall sprite, using five sprites. This is a little risky, since the NES can actually only display eight sprites per horizontal scanline. But given that the scarf is only two scanlines tall, it's unlikely to cause much of a problem. *FORESHADOWING*

The graphical data for each sprite was added to the CHR ROM in pretty much the same way as background tile data, but my process for putting the sprites together was a lot less elegant. I didn't use any kind of tool to stitch the sprites together. Instead, for each frame of animation, I just sat down and hand-wrote each metasprite, one by one. Which took ages. I don't really have anything clever to say about this one, I just hammered away at the keys every time I needed a new sprite. Good job, me! Real game developer hours right there. Wh-

* Section 6: Movement, Collision, and Hitboxes

(talk about world collision)
(talk about subpixel movement)
(talk about sword hitboxes and why they are the way they are)
(leads to -> sword equip jingle -> sounds and music)

* Section 7: Sounds and Music

(talk about famistudio, assembly, and driver)
(emmy part!!!)
(ice key jingle -> leads to theatrics)

* Section 8: Text and Theatrics

(talk about displaying text)
(talk about cutscenes and the theatrics system -> leads to game intro)

* Section 9: Visual Effects (Intro, Spiral Pattern)

(talk about the game intro)
(talk about the spiral loader and how accidents can lead to cool outcomes, attribute table)
(messy things lead to interesting outcomes -> links to story)

* Section 10: The Story & The Final Boss

Almost all of the dialogue in the original Deltarune minigames has layers of metatext. The entities in the game talk to Kris, about their past, their nature, and even the way that we, the player, have control over them. The exploration of these metatextual themes in this and other parts of Deltarune are a huge part of why I find it so compelling. I'm really interested in seeing how the story being told develops, and how each layers of meaning and subtext intersects with the others. Because of that, and because the game was changed so much from its source material by various circumstances outside my control, it felt to me a little hollow to make an exact clone of the Deltarune minigames. So, instead, I started changing the dialogue and writing my own story that reflected how this game is both related to and separate from its inspiriation; how the constraints of working on an old console like this create certain differences, and how building things can be messy and how the results can be imperfect but still interesting, and how full of their creator's personality they become as a result.
I also wanted to write my own metatext about how this game *is* a fangame, and how the player playing it is probably only playing it because they've already seen everything in it in another, quote-unquote "real" game, how it's all familiar to them. So making things that are familiar slightly unfamiliar, and shrinking parts of the world, and calling that out explicitly - these things all contribute to the final finished story.

And of course, to mirror the way that the original story of this 8-bit world culminates in a conversation with a strange entity that seems to be aware of far more than it should be, I wanted to make my own boss.
Enter: this little guy!

Before this video, I mentioned in my game's comment section that I have a name for this guy, but I wanted to see what other people came up with. Well, I'll let you know his true name - but only after I've read you some of the most amusing names you guys came up with for him.
So, let's see here...
We've got: Eyeballs, Orach, Bytesize, Other One, EROM, Crumbs, John No-Mantle, just "John", Bob Cape, W.D. Johnny, John... Egbert..., John Exp Cruncher, and, with love, Googley Eyed Bitch.
I think these are all fantastic. I love them all - and if you have a name of your own you want to add to the pile, be sure to leave it in the comments of this video or on the game's page. But now, the moment you've been waiting for... I can now reveal the name I always had for him!
His name...
is...
Twisted!
That might not be such a surprise, given the name of the music track that plays when you fight him in his second phase, but there you go.
And check this out - here's a bunch of concept art of him, straight out of my notebooks. Sometimes you just can't beat pen and paper when you're planning something out, you know? When your mind wanders a bit, you can doodle a little guy like this on the page, and then decide to make him your entire life for three months straight.
It was really fun coming up with his unique attacks. Right at the start, I wanted him to be able to interact with the HUD of the game - because of the way the NES screen resolution is much bigger than the rooms, I really wanted to make use of that space in the borders. After the player has gotten used to playing the entire thing in this little window, I thought it'd be really fun to have Twisted break the borders and fly around "outside" the game, as it were!
His fight and monologue at the end were fun little spots to add just a little extra special touch to the fangame, with the help of one weird NES display quirk. You see, one colour in the NES palette is forbidden. It's at location 0x0D; it looks like black, like all the other black colours in the palette, but it's actually a little bit bugged. You see, the exact shade of black this generates on the video signal is slightly too dark for the video signal specification. When an older TV receives this shade of black, it can sometimes be tricked into thinking its receiving the blank space between frames, so it starts displaying all kinds of weird effects. The colour 0x0D is literally "darker than dark", as far as a TV is concerned... it's just so thematically perfect for a Deltarune fangame that I couldn't resist it. So, when you hit Twisted, his hurt frames will occasionally flash this colour; and at the end, the world, as it dissolves, eventually fades to this colour too. So someone out there, playing it on hardware, on just the right TV... will see bizarre visual glitches when they slash Twisted with the sword!

* Section 11: Wrapping Up

Well, I think that's nearly everything wanted to say, except for one more thing! This video turned out way, way bigger than I thought it was going to be; even just writing this script, it's taken a long time. It's the first time I've ever made anything this in-depth on YouTube before, I normally just post gameplay snippets, livecoding stream bits, weird YTPs, and other assorted junk, so this has been super different. It's been really, really fun! And I hope you enjoyed it too. Most of all, I hope that this has inspired some of you to maybe take a crack at making some NES homebrew of your own. And, as thanks to the NES development and Deltarune communities, I'm releasing my source code and LDTK project files for anyone to look at and modify and make something of their own out of. I've gone through it and added a bunch of extra comments and stuff to try and make it a little easier to read. As I've mentioned before, it's real messy, but hopefully you can get something out of it! Thanks so much for watching my video, and I hope you have a great day! Bye!
