#+title:MANTLE.NES Video Script

* Section 0: About the Video & Acknowledgements

Hi! I'm drmelon, and recently I worked on a half-demake, half-fangame for the original NES, based on a certain set of minigames from Deltarune Chapter 3. If you'd like to play it, you can check it out on my itch page, which I've linked in the description. Of course, it contains spoilers for Deltarune Chapter 3, as does this video - so go and play Deltarune first, so you don't get spoiled!

...

Now that the spoiler alert is done, welcome!
I wanted to make a video to share some of the inner workings of MANTLE.NES with everyone. I love watching videos from channels like Retro Mechanics Explained, or Wye's series on rebuilding Super Mario World from scratch in the Godot engine; I always find the way they share the technical details of retro games to be fascinating and informative, and so I wanted to do something similar for everyone who was curious about this fangame.

First though, there's a few people I want to thank.

I'd first like to thank leafcodes, for her awesome music. Her NES arrangements of the Sword Route tracks from Deltarune are fantastic and super faithful to the originals, and her own unique track, TWISTED, is absolutely awesome. Huge thanks to her for making this game sound as good as it does! I've linked her bandcamp in the description, go check it out!
I want to thank Bro3256 for the awesome playthrough video on hardware - it's really, really cool to see the game running on an actual NES, and the video also helped a lot of people find my fangame. Thank you for putting it out there!
Next, I want to thank everyone involved with the NES homebrew development scene; absolutely none of what I managed to make would even be slightly possible without the hard work of so many people.
Finally, I want to list out the tools I used to make this game on the screen - I'll link them all in the description so you can check them out too if you're interested. These made my life so much easier, and I'll talk more in depth about how I used them as the video goes on.

Alright, with my thanks and gratitude given out, let's get into why and how I got started with the project!

* Section 1: Why?

When I played Deltarune Chapter 3 back in June, I was immediately struck by how much love and care was poured into the Tenna board games. They really do feel and play like early Zelda titles, and the way the games are presented feels very internally consistent - it really sells the idea that this is some in-world console being represented. It reminded me of other fantasy consoles, like Lexaloffle's PICO-8 or the LX system from Mossmouth's UFO 50; the way that they have their own limitations and restraints that allow them to replicate the exact feeling of playing games from the mid-to-late eighties. And when I got to the S-Rank room, and found the backstage console and started playing... I mean, wow! The way the game unfolds builds up such a specific atmosphere, it was kind of electrifying. I remember being a kid, playing on the Megadrive and on the family MS-DOS PC, finding weird buggy secrets - there's a kind of gripping, transgressive fear, where you kind of feel your brain yelling "WE SHOULDN'T BE HERE!" but you somehow can't stop yourself from exploring... until you make the console glitch out in a weird way, and you hammer the reset button like your life depends on it! In case, you know, it comes alive and tries to eat you or something. I was a normal kid and grew up to be completely normal.

Playing the minigames reminded me of those feelings; the way it's like a strange, bleak reflection of the fun stuff you just played, and the way it mirrors the evil routes in Undertale contribute to that broken-and-creepy feeling, and it left me wondering how many kids were feeling that same excited terror I once felt.

So with the really impressive fantasy console stuff, and the big impression it left on me, I very quickly started thinking about how I could demake the game for a real console. So quickly that I actually started this project less
than a week after Deltarune Chapter 3 came out!

I was already familiar with programming on the NES, at least a little bit. But, I hadn't tried anything close to this scale before, so I knew it'd be a slightly longer journey - and because of that familiarity, I knew right off the bat that I'd have to make some changes or find ways to adapt things differently. I did initially intend to try and stay as close to a 1-to-1 demake as I could, but as things began to change more and more, I thought it would be a lot more fun (and a little bit metatextually more accurate) to make larger changes, and build it into part of a cohesive narrative.

So, with my rationale described and that little bit of background, let's get into the actual technical nuts and bolts...

* Section 2: The Cartridge

I could have written the entire thing in 6502 Assembly. Assembly is a low-level programming language where you write the machine code instructions you want the processor to perform; you're directly commanding the console's processor. It might seem complex at first, but it's actually simpler in a lot of ways than writing more abstract code, since there's only so much you can do. However, it would have taken me a much longer time to get everything I wanted written, and I wanted to build this game during my limited free time in the evenings and weekends, so instead I decided to use the C programming language.

C is a compiled language; I write more abstract code in a way that lets me ignore the exact instructions that the CPU needs to execute, and instead focus on the logic and arithmetic I want to compute instead. Then, the compiler (in this case, CC65) turns my source code into the same assembly instructions I would have written manually. It can't always do this in the most 100% efficient way, but C compilers these days generate very, very optimized code most of the time, so it's definitely worth trading a little runtime and storage efficiency for saving myself a bunch of real-world time.

To kick things off, I used a tool called "create-nes-game" to start a new project; this is a fantastic tool that will automatically install the compiler, assembler, optional C libraries, a NES emulator, and set up some sensible defaults for the NES cartridge - such as which mapper chip I wanted to use...

One of the interesting things about cartridge-based games is the fact that the game cartridges themselves are pieces of independent hardware. The pins in the cartridge slot allow the CPU of the NES to communicate with the chips inside the cartridge directly - making an actual, physical connection to the read-only memory (or ROM) chips, which the console interprets as a section of memory usually beginning at the address 0x8000 and ending at 0xFFFF, the biggest number the console can represent in its 16-bit address space. The earliest NES games like the original Super Mario Bros came on a cartridge format known in the NES development community as "NROM"; the cartridge consisted of up to 32 kilobytes of PRG (program) ROM, which contained all of the game's code and audio, and 8 kilobytes of CHR (character) ROM, which contained the entire game's graphics data. This really isn't a lot of space to work with, so what happens if your game is just a little bit too big to fit in an NROM?

This problem can be overcome thanks to the aforementioned way that cartridge-based games are built using hardware - if you need more ROM space, why not just add more ROM chips to the cartridge? Well, the console doesn't know you've done this, and so the instructions that it uses to communicate with the cartridge have no way to access these new chips, since it can still only see a window from 0x8000 to 0xFFFF. So, you add an extra chip called a "mapper chip". It reserves a few memory addresses for its own registers; when these addresses are filled with values, it can read the values and switch which of the ROM chips are connected to the console's pins. The console doesn't actually "know" the connections are being changed like this; it all just looks like regular ROM space, but it works - as long as you don't need something from two different places at exactly the same time, that is! And because they are hardware, mapper chips can do a lot more than just increase the amount of ROM you have available, and can actually add new features that weren't there before.

When Nintendo wanted to bring the first entry in the Legend of Zelda series to the international market, they had a problem. You see, Zelda 1 was originally released for the Famicom Disk System which was an add-on peripheral for the NES' original Japanese incarnation, the Famicom (short for Family Computer). The NES was designed as a gaming-only entertainment system rather than a home computer, to thread the needle between the recent market crash of home computers in the US, and the massive popularity of relatively affordable home computers in the European market.

As the name suggests, the Disk System used removable disks, similar in nature to floppy disks. These had a larger capacity of 64 kilobytes on each side - a total of 128 kilobytes! Zelda 1 was written for this new format, and took full advantage of the space available for its large interconnected world. But, of course, when it was time to bring it to the NES, there wasn't enough room on the standard NROM cartridges for the game! Not only that, but the game allowed players to save their progress in save files on the disk, which wasn't possible on the NES. And playing Zelda 1 without being able to save would be pretty painful.

Nintendo designed a mapper chip called the "MMC1" in order to build the cartridge-based version of Zelda 1. The chip massively increased the storage capacity, up to a maximum of 256 kilobytes of PRG ROM and 128 kilobytes of CHR ROM. It also supported battery-backed SRAM; a writable chip that could store save data as long as a battery inside the cartridge supplied power to it, which meant players could save their game just like the disk system version of Zelda 1! This made the chip a very popular choice, and more than 300 games used the MMC1. I really wanted to continue the same callbacks that the Deltarune minigames were making to older Zelda titles, so I decided to build my fangame with this chip in mind!

* Section 3: Rooms, Tiles, and Colours

The game's resolution was the first thing I had to contend with. The game world is divided up into rooms that take up most of the screen's display; the characters can travel between rooms at the edges, and the screen will scroll over to reveal the next room. Most game consoles from the era that Deltarune's fantasy console mimics drew backgrounds using Tiles, and the Deltarune fantasy console is no different.

Each room in the game appears to consist of a grid of 12 by 8 tiles. Each tile is 16 pixels wide, and 16 pixels tall. However, the game's HUD is displayed in an area 16 pixels tall along the top of the screen, and can be divided into smaller 8-by-8 tiles; so it's probably more accurate to say that the main play area also uses 8x8 tiles, and is 24 tiles wide and 16 tiles tall. Combining this with the HUD area, the total console resolution is 24 tiles by 18 tiles - or 192 by 144, a 4:3 aspect ratio - which is the same aspect ratio as Deltarune itself, and the most common aspect ratio for TVs in the 80s and 90s. It's also the same vertical resolution as the original Game Boy and Game Boy Color handhelds, but they were a little narrower, at only 160 pixels wide.

The output resolution of the NES is actually quite a bit bigger. It supports a maximum resolution of 256x240 pixels, or 32x30 tiles, at the slightly awkward aspect ratio of 8:7. On top of this, when outputting a 60Hz NTSC video signal rather than a 50Hz PAL signal, the top and bottom 8 pixels are cut off, resulting in a resolution of 256x224 pixels, or 32x28 visible tiles.

So, this means that the rooms
