#+title:MANTLE.NES Video Script

* Section 0: About the Video & Acknowledgements

Hi! I'm drmelon, and recently I worked on a half-demake, half-fangame for the original NES, based on a certain set of minigames from Deltarune Chapter 3. If you'd like to play it, you can check it out on my itch page, which I've linked in the description. Of course, it contains spoilers for Deltarune Chapter 3, as does this video - so go and play Deltarune first, so you don't get spoiled!

...

So, welcome!
I wanted to make a video to share some of the inner workings of MANTLE.NES with everyone. I love watching videos from channels like Retro Mechanics Explained, or Wye's series on rebuilding Super Mario World from scratch in the Godot engine; I always find the way they share the technical details of retro games to be fascinating and informative, and so I wanted to do something similar for everyone who was curious about this fangame.

First though, there's a few people I want to thank.

I'd first like to thank leafcodes, for her awesome music. Her NES arrangements of the Sword Route tracks from Deltarune are fantastic and super faithful to the originals, and her own unique track, TWISTED, is absolutely awesome. Huge thanks to her for making this game sound as good as it does! I've linked her bandcamp in the description, go check it out!
I want to thank Bro3256 for the awesome playthrough video on hardware - it's really, really cool to see the game running on an actual NES, and the video also helped a lot of people find my fangame. Thank you for putting it out there!
Next, I want to thank everyone involved with the NES homebrew development scene; absolutely none of what I managed to make would even be slightly possible without the hard work of so many people.
Finally, I want to list out the tools I used to make this game on the screen - I'll link them all in the description so you can check them out too if you're interested. These made my life so much easier, and I'll talk more in depth about how I used them as the video goes on.

Alright, with my thanks and gratitude given out, let's get into it!

* Section 1: MANTLE.NES

When I played Deltarune Chapter 3 back in June, I was immediately struck by how much love and care was poured into the Tenna board games. They really do feel and play like early Zelda titles, and the way the games are presented feels very consistent - it really sells the idea that this is some in-world console being represented. It reminded me of other fantasy consoles, like PICO-8 or the LX system from UFO 50; the way that they have their own limitations and restraints that allow them to replicate the exact feeling of playing games from the mid-to-late eighties. And when I got to the S-Rank room, and found the backstage console and started playing... I mean, wow! The way the game unfolds builds up such a specific atmosphere, it was kind of electrifying. I remember being a kid, playing on the Megadrive, finding weird buggy secrets - there's a kind of gripping, transgressive fear, where you kind of feel your brain yelling "WE SHOULDN'T BE HERE!" but you somehow can't stop yourself from exploring... until you make the console glitch out in a weird way, and you hammer the reset button like your life depends on it!

Playing the minigames reminded me of those feelings; the way it's like a strange, bleak reflection of the fun stuff you just played, and the way it mirrors the evil routes in Undertale contribute to that broken-and-creepy feeling, and it left me wondering how many kids were feeling that same excited terror I once felt.

So with the really impressive fantasy console stuff, and the big impression it left on me, I very quickly started thinking about how I could demake the game on the NES. So quickly that I actually started this project less than week after Deltarune Chapter 3 came out!

I was already familiar with programming on the NES, but I hadn't tried anything of this scale before, so I knew it'd be a fun journey - and because of that familiarity, I knew right off the bat that I'd have to make some changes or find ways to adapt things differently. I did initially intend to try and stay as close to a 1-to-1 demake as I could, but as things began to change more and more, I thought it would be a lot more fun (and a little bit metatextually more accurate) to make larger changes, and build it into part of a cohesive narrative.

So, with my rationale described and that little bit of background, let's get into the actual technical nuts and bolts, starting with...

* Section 2: Rooms, Tiles, and Colours

This was the first thing I had to contend with. Most game consoles from the era that Deltarune's fantasy console mimics drew backgrounds using Tiles, and the Deltarune console is no different. Each room in the game appears to consist of a grid of 12 by 8 tiles. Each tile is 16 pixels wide, and 16 pixels tall. However, the game's HUD is displayed in an area 16 pixels tall along the top of the screen, and can be divided into smaller 8-by-8 tiles; so it's probably more accurate to say that the main play area also uses 8x8 tiles, and is 24 tiles wide and 16 tiles tall. Combining this with the HUD area, the total console resolution is 24 tiles by 18 tiles - or 192 by 144.
This is technically the same resolution as a 144p YouTube video!
